[package]
name = "deox-codegen-rust"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
thiserror.workspace = true
deox-error.workspace = true
deox-ast.workspace = true
syn.workspace = true
quote.workspace = true
proc-macro2.workspace = true
prettyplease.workspace = true

[dev-dependencies]
insta.workspace = true
