//! `buff-mock` — Mocking framework for the Buff language.
//!
//! Provides `Mock<Trait>` — a generic mock instance with `expect` /
//! `verify` / `spy` semantics — plus a codegen-time helper
//! [`lower_mock_for_trait`] that emits the trait impl as `syn::Item`s.
//!
//! # Why this exists
//!
//! Every major language ecosystem has a mocking framework (Rust:
//! [`mockall`](https://docs.rs/mockall/), Python: `unittest.mock`,
//! C#: Moq). T22 (API compatibility spike) and T23 (flagship tests)
//! both need mock-based testing. This crate is the foundational layer
//! for both.
//!
//! # Design (per T3 macro spike DEFER outcome)
//!
//! Rust has no way to auto-derive an arbitrary trait impl without
//! procedural macros. The T3 spike deferred the macro system
//! (`.sisyphus/decisions/macro-system-v1x.md`) and recommended runtime
//! workarounds. `buff-mock` follows that recommendation:
//!
//! 1. The **runtime API** (`Mock`, `ExpectationBuilder`, `SpyHandle`)
//!    is a pure-Rust library usable directly from any test.
//! 2. The **codegen helper** [`lower_mock_for_trait`] emits the
//!    trait impl as a `syn::Item` — `buff-lang-codegen-rust` can call
//!    it in the future to expand `@mock let m: T = Mock.new()` into
//!    the right `impl T for Mock<T>` block. (Future integration; the
//!    MVP ships WITHOUT requiring parser/AST/codegen-rust changes.)
//!
//! # Quick start
//!
//! ```ignore
//! use buff_mock::{Mock, ReturnValue};
//!
//! // User-defined trait:
//! trait Greeter { fn greet(&self, name: String) -> String; }
//!
//! // User-written mock impl (or generated by `lower_mock_for_trait`):
//! impl Greeter for Mock<dyn Greeter> {
//!     fn greet(&self, name: String) -> String {
//!         self.record_call("greet", vec![buff_mock::ArgumentValue::String(name)]);
//!         match self.lookup_return("greet", &[]) {
//!             Some(ReturnValue::String(s)) => s,
//!             _ => String::new(),
//!         }
//!     }
//! }
//!
//! // Test:
//! let mock = Mock::<dyn Greeter>::new();
//! mock.expect("greet").returning(ReturnValue::String("hello".into()));
//! assert_eq!(mock.greet("alice".into()), "hello");
//! mock.verify().unwrap();
//! ```
//!
//! # Spy pattern
//!
//! ```ignore
//! let spy = mock.spy("greet");
//! mock.greet("alice".into());
//! mock.greet("bob".into());
//! assert_eq!(spy.call_count(), 2);
//! assert_eq!(spy.args()[0][0], ArgumentValue::String("alice".into()));
//! ```
//!
//! # References
//!
//! - Plan: `.sisyphus/plans/buff-v1x-frameworks.md` task T25 (lines 780-855).
//! - Macro spike decision: `.sisyphus/decisions/macro-system-v1x.md`.
//! - `mockall` (Rust): <https://docs.rs/mockall/latest/mockall/>.
//! - `unittest.mock` (Python): <https://docs.python.org/3/library/unittest.mock.html>.

pub mod error;
pub mod expectation;
pub mod lowering;
pub mod mock;
pub mod record;
pub mod spy;
pub mod state;
pub mod times;

pub use error::{MockError, MockResult};
pub use expectation::{Expectation, ExpectationBuilder};
pub use lowering::lower_mock_for_trait;
pub use mock::Mock;
pub use record::{ArgumentValue, CallRecord, ReturnValue};
pub use spy::SpyHandle;
pub use state::MockState;
pub use times::Times;

/// Crate version (matches `Cargo.toml`).
pub const CRATE_VERSION: &str = env!("CARGO_PKG_VERSION");

#[cfg(test)]
mod smoke_tests {
    //! Smoke tests at the crate root — assert that the public API
    //! surface compiles and the basic shape works. Full behavioral
    //! coverage lives in `tests/mock_tests.rs`.

    use super::*;

    trait SampleTrait {
        fn ping(&self) -> bool;
    }

    impl SampleTrait for Mock<dyn SampleTrait> {
        fn ping(&self) -> bool {
            self.record_call_no_args("ping");
            match self.lookup_return_no_args("ping") {
                Some(ReturnValue::Bool(b)) => b,
                _ => false,
            }
        }
    }

    #[test]
    fn smoke_mock_constructs_and_returns_default() {
        let m = Mock::<dyn SampleTrait>::new();
        assert!(!m.ping());
        assert_eq!(m.call_count_for("ping"), 1);
    }

    #[test]
    fn smoke_expect_returning_overrides_default() {
        let m = Mock::<dyn SampleTrait>::new();
        m.expect("ping").returning(ReturnValue::Bool(true));
        assert!(m.ping());
    }

    #[test]
    fn smoke_verify_passes_when_times_satisfied() {
        let m = Mock::<dyn SampleTrait>::new();
        m.expect("ping").times(1);
        let _ = m.ping();
        assert!(m.verify().is_ok());
    }

    #[test]
    fn smoke_spy_records_args() {
        trait Greeter {
            fn greet(&self, name: String) -> String;
        }
        impl Greeter for Mock<dyn Greeter> {
            fn greet(&self, name: String) -> String {
                self.record_call(
                    "greet",
                    vec![ArgumentValue::String(name)],
                );
                match self.lookup_return("greet", &[]) {
                    Some(ReturnValue::String(s)) => s,
                    _ => String::new(),
                }
            }
        }
        let m = Mock::<dyn Greeter>::new();
        let spy = m.spy("greet");
        let _ = m.greet("alice".into());
        let _ = m.greet("bob".into());
        assert_eq!(spy.call_count(), 2);
        assert_eq!(
            spy.calls().first().map(|r| r.args.clone()),
            Some(vec![ArgumentValue::String("alice".into())])
        );
    }
}
