//! Integration tests for the `buff-audit` crate — public API surface.
//!
//! Covers every public fn per the T26 spec:
//! - `keypair()` — fresh Ed25519 CSPRNG keypair.
//! - `sign(data, secret_hex)` — detached signature.
//! - `verify(data, sig_hex, public_hex)` — strict verify, returns Bool.
//! - `scan(project_root)` — manifest substring scan.
//! - `scan_with_detail(project_root)` — same but with remediation hints.
//! - `known_advisories()` — static DB enumeration.
//!
//! Pure-Rust; no network; deterministic advisory DB.

use buff_audit::{keypair, known_advisories, scan, scan_with_detail, sign, verify, AdvisoryHit,
    AuditError, MANIFEST_PATHS};

#[test]
fn manifest_paths_priority_chain_lists_buff_lock_first() {
    assert_eq!(MANIFEST_PATHS[0], "buff.lock");
    assert_eq!(MANIFEST_PATHS[1], "Cargo.lock");
    assert_eq!(MANIFEST_PATHS[2], "buff.toml");
}

#[test]
fn known_advisories_returns_seed_entries() {
    let list = known_advisories();
    assert!(!list.is_empty(), "DB should seed with at least 1 entry");
    assert!(list.contains(&"RUSTSEC-2020-0159".to_string()));
}

#[test]
fn scan_returns_empty_when_no_manifest_exists() {
    let tmp = std::env::temp_dir().join(format!(
        "buff-audit-test-empty-{}",
        std::process::id()
    ));
    let _ = std::fs::remove_dir_all(&tmp);
    std::fs::create_dir_all(&tmp).expect("mkdir");
    let hits = scan(&tmp).expect("scan on empty dir");
    assert!(hits.is_empty(), "empty project should have 0 advisories");
    let _ = std::fs::remove_dir_all(&tmp);
}

#[test]
fn scan_finds_vulnerable_chrono_in_cargo_lock() {
    let tmp = std::env::temp_dir().join(format!(
        "buff-audit-test-vuln-cargo-{}",
        std::process::id()
    ));
    let _ = std::fs::remove_dir_all(&tmp);
    std::fs::create_dir_all(&tmp).expect("mkdir");
    let cargo_lock = tmp.join("Cargo.lock");
    std::fs::write(
        &cargo_lock,
        r#"# This file is automatically @generated by Cargo.
[[package]]
name = "chrono"
version = "0.4.19"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "1e37c4b6c7c7c7c7c7c7c7c7c7c7c7c7c7c7c7c"
"#,
    )
    .expect("write Cargo.lock");
    let hits = scan(&tmp).expect("scan");
    assert!(
        hits.contains(&"RUSTSEC-2020-0159".to_string()),
        "should fire on chrono 0.4.19"
    );
    let _ = std::fs::remove_dir_all(&tmp);
}

#[test]
fn scan_finds_vulnerable_chrono_in_buff_toml() {
    let tmp = std::env::temp_dir().join(format!(
        "buff-audit-test-vuln-buff-{}",
        std::process::id()
    ));
    let _ = std::fs::remove_dir_all(&tmp);
    std::fs::create_dir_all(&tmp).expect("mkdir");
    let buff_toml = tmp.join("buff.toml");
    std::fs::write(
        &buff_toml,
        r#"[package]
name = "demo"
version = "0.1.0"

[dependencies]
chrono = "0.4.19"
"#,
    )
    .expect("write buff.toml");
    let hits = scan(&tmp).expect("scan");
    assert!(
        hits.contains(&"RUSTSEC-2020-0159".to_string()),
        "should fire on chrono in buff.toml"
    );
    let _ = std::fs::remove_dir_all(&tmp);
}

#[test]
fn scan_skips_patched_versions() {
    let tmp = std::env::temp_dir().join(format!(
        "buff-audit-test-patched-{}",
        std::process::id()
    ));
    let _ = std::fs::remove_dir_all(&tmp);
    std::fs::create_dir_all(&tmp).expect("mkdir");
    let cargo_lock = tmp.join("Cargo.lock");
    std::fs::write(
        &cargo_lock,
        r#"[[package]]
name = "chrono"
version = "0.4.20"
"#,
    )
    .expect("write Cargo.lock");
    let hits = scan(&tmp).expect("scan");
    assert!(
        hits.is_empty(),
        "patched chrono 0.4.20 should NOT trigger advisory"
    );
    let _ = std::fs::remove_dir_all(&tmp);
}

#[test]
fn scan_with_detail_returns_advisory_hit_struct() {
    let tmp = std::env::temp_dir().join(format!(
        "buff-audit-test-detail-{}",
        std::process::id()
    ));
    let _ = std::fs::remove_dir_all(&tmp);
    std::fs::create_dir_all(&tmp).expect("mkdir");
    let cargo_lock = tmp.join("Cargo.lock");
    std::fs::write(
        &cargo_lock,
        r#"[[package]]
name = "chrono"
version = "0.4.19"
"#,
    )
    .expect("write Cargo.lock");
    let hits = scan_with_detail(&tmp).expect("scan_with_detail");
    assert_eq!(hits.len(), 1);
    let expected = AdvisoryHit {
        id: "RUSTSEC-2020-0159".to_string(),
        package: "chrono".to_string(),
        patched: "0.4.20".to_string(),
    };
    assert_eq!(hits[0], expected);
    let _ = std::fs::remove_dir_all(&tmp);
}

#[test]
fn keypair_returns_two_distinct_64char_hex_strings() {
    let (pk, sk) = keypair().expect("keypair");
    assert_eq!(pk.len(), 64);
    assert_eq!(sk.len(), 64);
    assert_ne!(pk, sk, "public != secret");
    let (pk2, _) = keypair().expect("keypair 2");
    assert_ne!(
        pk, pk2,
        "two CSPRNG keypairs should differ (with overwhelming probability)"
    );
}

#[test]
fn sign_rejects_short_secret_key_with_bad_key_error() {
    let err = sign(b"data", "abcd").unwrap_err();
    assert!(matches!(err, AuditError::BadKey(_)));
}

#[test]
fn sign_rejects_invalid_hex_secret_with_hex_error() {
    let err = sign(b"data", "ZZ").unwrap_err();
    assert!(matches!(err, AuditError::Hex(_)));
}

#[test]
fn verify_rejects_short_public_key_with_bad_key_error() {
    let sig = "00".repeat(64);
    let err = verify(b"data", &sig, "abcd").unwrap_err();
    assert!(matches!(err, AuditError::BadKey(_)));
}

#[test]
fn verify_rejects_short_signature_with_bad_signature_error() {
    let (pk, _) = keypair().expect("keypair");
    let err = verify(b"data", "abcd", &pk).unwrap_err();
    assert!(matches!(err, AuditError::BadSignature(_)));
}

#[test]
fn advisory_hit_eq_hash_derive_works() {
    let a = AdvisoryHit {
        id: "X".to_string(),
        package: "p".to_string(),
        patched: "1".to_string(),
    };
    let b = a.clone();
    assert_eq!(a, b);
    let set: std::collections::HashSet<AdvisoryHit> = [a].into_iter().collect();
    assert_eq!(set.len(), 1);
}
