//! Project scaffolding — templates and validation shared by `deox new` and
//! `deox init`.
//!
//! Templates are plain strings with a single `{name}` placeholder substituted
//! by [`render_template`]. They are deliberately simple (no TPL engine dep):
//! the v0.1 generated project is four small files, and a `str::replace` call
//! keeps the dependency surface minimal.
//!
//! [`validate_project_name`] enforces the same identifier rules the lexer will
//! later apply to symbols, plus a check against the 25 reserved keywords (see
//! `crates/deox-lexer/src/token.rs`).

/// Reserved Deox keywords (must match the lexer's keyword table).
///
/// Sourcing this as a static array here (instead of importing from the lexer)
/// keeps `deox new` / `deox init` decoupled from lexer internals — the keyword
/// list is small and stable for v0.1.
pub const KEYWORDS: &[&str] = &[
    "func", "let", "mut", "struct", "enum", "trait", "type", "if", "else", "for", "return",
    "break", "continue", "in", "match", "async", "spawn", "import", "export", "from", "as", "true",
    "false", "extern", "unsafe",
];

/// `deox.toml` manifest template.
///
/// `{name}` is replaced with the project name. The `edition` field tracks the
/// Deox language edition (semver-ish); v0.1 emits `"0.1"`.
pub const DEOX_TOML_TEMPLATE: &str = r#"[package]
name = "{name}"
version = "0.1.0"
edition = "0.1"
"#;

/// `src/main.deox` entry-point template.
///
/// `{name}` is referenced in a leading comment. The body is the canonical v0.1
/// "Hello, Deox!" program and is runnable via `deox run src/main.deox`.
pub const MAIN_DEOX_TEMPLATE: &str = r#"// {name} - generated by `deox new`
func main():
    print("Hello, Deox!")
"#;

/// `.gitignore` template emitted into the project root.
///
/// Ignores the cargo `target/` tree, the per-project `deox.lock`, and any
/// stray generated `.rs` files (the transpiler writes them next to the source
/// — keeping them out of VCS is the user's signal that they're build artifacts).
pub const GITIGNORE_TEMPLATE: &str = r#"target/
deox.lock
*.rs
"#;

/// `README.md` template — minimal usage instructions referencing `deox run`.
pub const README_TEMPLATE: &str = r#"# {name}

Generated by `deox new`.

## Run

```
deox run src/main.deox
```
"#;

/// Validate a project name.
///
/// Rules:
/// - Non-empty.
/// - Starts with an ASCII letter or underscore (not a digit, not unicode).
/// - Subsequent characters are ASCII alphanumeric or underscore.
/// - Not a reserved Deox keyword (see [`KEYWORDS`]).
///
/// # Errors
///
/// Returns a human-readable `String` describing the first violated rule. The
/// message is suitable for direct display to the user via `anyhow::Error::msg`.
pub fn validate_project_name(name: &str) -> Result<(), String> {
    if name.is_empty() {
        return Err("project name cannot be empty".to_string());
    }
    let first = name.chars().next().expect("checked non-empty above");
    if !first.is_ascii_alphabetic() && first != '_' {
        return Err(format!(
            "project name must start with a letter or underscore: `{name}`"
        ));
    }
    if !name.chars().all(|c| c.is_ascii_alphanumeric() || c == '_') {
        return Err(format!(
            "project name contains invalid characters (allowed: a-z, A-Z, 0-9, _): `{name}`"
        ));
    }
    if KEYWORDS.contains(&name) {
        return Err(format!(
            "invalid project name: `{name}` is a reserved Deox keyword"
        ));
    }
    Ok(())
}

/// Substitute the `{name}` placeholder in a template string.
///
/// Uses plain `str::replace`, which replaces *all* occurrences (templates may
/// reference the name multiple times, e.g. the README header and run command).
pub fn render_template(template: &str, name: &str) -> String {
    template.replace("{name}", name)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn render_template_replaces_single_occurrence() {
        let rendered = render_template(DEOX_TOML_TEMPLATE, "my_app");
        assert!(rendered.contains("name = \"my_app\""));
        assert!(!rendered.contains("{name}"));
    }

    #[test]
    fn render_template_replaces_multiple_occurrences() {
        let rendered = render_template(README_TEMPLATE, "demo");
        // README references the name twice: header + (potentially) usage.
        assert!(rendered.matches("demo").count() >= 1);
        assert!(!rendered.contains("{name}"));
    }

    #[test]
    fn keywords_table_has_25_entries() {
        // Mirrors the lexer keyword count; if either side changes the other
        // must follow.
        assert_eq!(KEYWORDS.len(), 25, "Deox has 25 reserved keywords");
    }
}
