//! T8 — Multi-crate emission mode.
//!
//! When a Buff program contains ES6-form `import { ... } from "./path.buff"`
//! declarations, emit one `.rs` file per Buff module instead of one
//! monolithic file. The root file gets `mod module_name;` declarations
//! plus `use module_name::{...};` imports, and each module's source is
//! written alongside. This enables rustc parallelism (each module compiles
//! independently) and improves incremental rebuilds.
//!
//! # Activation rule
//!
//! Multi-crate mode activates ONLY when the root Buff program has at
//! least one `import ... from "..."` declaration. Single-file programs
//! (no imports) bypass this mode entirely — the existing
//! [`crate::generate_rust`] single-file path is used unchanged (full
//! backwards compatibility for `buff run examples/ola.buff` etc.).
//!
//! # Output shape
//!
//! For a program `main.buff` containing `import { greet } from
//! "./greet.buff"`, the multi-crate output is:
//!
//! ```text
//! main.rs:                        // root file (rustc entry point)
//!     mod greet;
//!     use greet::greet;
//!     fn main() { println!("{}", greet("Buff")); }
//!
//! greet.rs:                       // sibling module file
//!     pub fn greeting_for(name: String) -> String { name }
//!     pub fn greet(name: String) -> String { greeting_for(name) }
//! ```
//!
//! The pipeline writes both files into a directory (alongside the root
//! `.buff` for source-relative pathing) and invokes `rustc main.rs`.
//!
//! # Recursive imports
//!
//! Each module is generated by filtering out `import` declarations and
//! lowering the rest via the standard [`RustCodegen`]. Transitively-
//! imported modules (module A imports module B) are flattened into the
//! ROOT's mod list — every transitively-reachable module file lives
//! alongside `main.rs`, and the importing module references it via `mod
//! b;` + `use b::*;` at its top. This avoids nested-directory `mod.rs`
//! complexity for v1.25 (a flat directory of `.rs` files is the simplest
//! shape that lets rustc parallelise).
//!
//! # Limitations (v1.25 first cut)
//!
//! - Legacy `import a.b.c as alias` form (no `from "..."`) is NOT
//!   handled — it has no file to link. The existing single-file
//!   codegen path returns an "unsupported" error for that form, which
//!   the pipeline surfaces unchanged.
//! - Per-import aliasing (`import { greet as g } from ...`) is not in
//!   the AST today (only the legacy form has `alias`); when it lands,
//!   the use-import lowering here will need to emit `use mod::greet as
//!   g;`.
//! - The module graph is collected by the PIPELINE (which has file
//!   access) and passed in as a flat `&[ParsedModule]`. Cycle detection
//!   is the pipeline's responsibility (it walks imports BFS and skips
//!   already-visited paths).

use std::collections::{BTreeMap, BTreeSet};

use proc_macro2::Span as ProcSpan;
use syn::{Ident, Item, ItemMod, Visibility};

use buff_lang_ast::Decl;
use buff_lang_error::{CodegenError, Diagnostic, Span as BuffSpan};

use crate::{format, RustCodegen};

/// Predicate: does this decls list use the ES6-form `import ... from
/// "..."` syntax (the multi-module form)?
///
/// Returns `true` if any top-level decl is an [`Decl::ImportDecl`] with
/// a populated `from_path` field. The legacy `import a.b.c as alias`
/// form (no `from_path`) is NOT multi-crate — it has no file to link,
/// so the predicate returns `false` and single-file codegen handles it
/// (currently by erroring with "import codegen unsupported", matching
/// pre-T8 behaviour).
///
/// The pipeline consults this predicate before deciding which codegen
/// path to take: `true` → [`generate_multi_crate`], `false` → existing
/// [`crate::generate_rust`].
pub fn uses_multi_crate(decls: &[Decl]) -> bool {
    decls.iter().any(|d| {
        matches!(
            d,
            Decl::ImportDecl(imp) if imp.from_path.is_some()
        )
    })
}

/// One parsed Buff module contributing to a multi-crate build.
///
/// Built by the pipeline (which has filesystem access) by reading +
/// lexing + parsing each transitively-referenced `.buff` file. The
/// codegen-rust crate is purely AST→Rust, so it consumes these as
/// already-parsed inputs.
#[derive(Debug, Clone)]
pub struct ParsedModule {
    /// Sanitised Rust ident for this module (e.g. `greet` for
    /// `./greet.buff`). Used as the `mod <ident>;` name AND the
    /// on-disk filename (`<ident>.rs`).
    pub ident: String,
    /// The original `from "..."` path as written in the importing
    /// Buff source (e.g. `"./greet.buff"`). Kept for diagnostics +
    /// duplicate-import detection (the pipeline de-duplicates on this
    /// string, not on the sanitised ident, so `./greet.buff` and
    /// `./greet.v2.buff` produce distinct idents `greet` and
    /// `greet_v2`).
    pub from_path: String,
    /// The parsed declarations of the module file.
    pub decls: Vec<Decl>,
}

/// Output of multi-crate emission (T8).
///
/// Returned by [`generate_multi_crate`]. The pipeline writes
/// `root_source` to `<root_stem>.rs` and each entry of `modules` to
/// `<ident>.rs`, all in the same directory, then invokes `rustc` on
/// the root.
#[derive(Debug, Clone)]
pub struct MultiCrateOutput {
    /// Source of the root `.rs` file. Contains `mod X;` declarations
    /// for each module + `use X::...;` imports + the non-import decls
    /// of the root Buff module lowered as usual.
    pub root_source: String,
    /// Map from module ident → generated Rust source for that module.
    /// Emitted in `BTreeMap` iteration order (deterministic across
    /// runs, independent of hash seed — the T29 flaky-test lesson).
    pub modules: BTreeMap<String, String>,
    /// Aggregated extern-crate dependency set across root + all
    /// modules. The pipeline consults this when wiring up the (future)
    /// Cargo project or `buff.toml [rust-deps]` block.
    pub extern_crates: BTreeSet<String>,
}

/// Sanitise a Buff `from "..."` path into a valid Rust mod ident.
///
/// Rules:
/// - Strip leading `./` and any number of `../` prefixes.
/// - Take the file stem (everything before the first `.` in the last
///   path segment).
/// - Replace non-ident chars (`-`, `.`, `/`, etc.) with `_`.
/// - Prefix `m` if the result starts with a digit (Rust idents can't
///   start with `[0-9]`).
/// - Fall back to `module` if the result is empty.
///
/// # Examples
///
/// ```ignore
/// assert_eq!(module_ident_from_path("./greet.buff"), "greet");
/// assert_eq!(module_ident_from_path("./utils/helpers.buff"), "helpers");
/// assert_eq!(module_ident_from_path("./123_start.buff"), "m123_start");
/// assert_eq!(module_ident_from_path("./my-mod.buff"), "my_mod");
/// ```
pub fn module_ident_from_path(from_path: &str) -> String {
    // Strip leading "./" or "../" sequences (any number).
    let mut trimmed = from_path;
    loop {
        let stripped = trimmed
            .strip_prefix("./")
            .or_else(|| trimmed.strip_prefix("../"));
        match stripped {
            Some(s) => trimmed = s,
            None => break,
        }
    }
    // Take the last path segment as the file stem source. `rsplit('/').next()`
    // is always `Some` for any string (including the empty string — it
    // returns `Some("")`), so no `unwrap_or` fallback is needed.
    let last_segment = trimmed.rsplit('/').next().unwrap_or(trimmed);
    let stem = last_segment
        .rsplit_once('.')
        .map(|(s, _)| s)
        .unwrap_or(last_segment);
    // Replace non-ident chars with '_' and collect.
    let mut sanitised: String = stem
        .chars()
        .map(|c| {
            if c.is_ascii_alphanumeric() || c == '_' {
                c
            } else {
                '_'
            }
        })
        .collect();
    // Collapse leading underscores (a leading `_` is a valid Rust
    // ident but reads oddly; strip them so `_foo` becomes `foo`).
    while sanitised.starts_with('_') && sanitised.len() > 1 {
        sanitised.remove(0);
    }
    // Prefix `m` if starts with a digit.
    if sanitised
        .chars()
        .next()
        .map(|c| c.is_ascii_digit())
        .unwrap_or(false)
    {
        sanitised.insert(0, 'm');
    }
    // Avoid the empty case.
    if sanitised.is_empty() {
        sanitised = "module".to_string();
    }
    sanitised
}

/// Lower a single Buff module to formatted Rust source (T8 helper).
///
/// Filters out `ImportDecl` and `ReexportDecl` (they are multi-file
/// module-graph concerns — single-module codegen skips them) and lowers
/// the rest via the standard [`RustCodegen::generate`]. The pipeline
/// uses this for each module in a multi-crate build.
///
/// Exported separately from [`generate_multi_crate`] so the pipeline
/// can reuse it for individual module files when the project structure
/// is already known.
///
/// # Returns
///
/// `(source, extern_crates)` — the formatted Rust source for the
/// module + the extern-crate deps the module pulls in (recorded by
/// [`RustCodegen::extern_crates`] during lowering).
pub fn generate_module_source(decls: &[Decl]) -> Result<(String, BTreeSet<String>), CodegenError> {
    let filtered: Vec<Decl> = decls
        .iter()
        .filter(|d| !is_module_graph_decl(d))
        .cloned()
        .collect();
    let mut codegen = RustCodegen::new();
    let file = codegen.generate(&filtered)?;
    let extern_crates = codegen.extern_crates().clone();
    Ok((format(&file), extern_crates))
}

/// `true` when `decl` is a module-graph declaration that should be
/// filtered out during per-module codegen.
///
/// - [`Decl::ImportDecl`] — resolved into `mod X; use X::*;` at the
///   importing module's top, not lowered inside the module body.
/// - [`Decl::ReexportDecl`] — already filtered by the existing
///   `generate()` loop; we filter here too for direct callers of
///   [`generate_module_source`].
fn is_module_graph_decl(decl: &Decl) -> bool {
    matches!(decl, Decl::ImportDecl(_) | Decl::ReexportDecl(_))
}

/// Collect the ES6-form imports from `decls` as `(from_path, names,
/// wildcard)` tuples, preserving source order.
///
/// Used by [`generate_multi_crate`] to build the `mod` + `use` item
/// lists for the root file. The legacy `import a.b.c as alias` form
/// (no `from_path`) is skipped — it has no module file to link.
fn collect_es6_imports(decls: &[Decl]) -> Vec<(&str, Vec<String>, bool)> {
    let mut out = Vec::new();
    for d in decls {
        if let Decl::ImportDecl(imp) = d {
            if let Some(from) = &imp.from_path {
                let names: Vec<String> = imp.imports.iter().map(|n| n.name.clone()).collect();
                out.push((from.as_str(), names, imp.wildcard));
            }
        }
    }
    out
}

/// Build a `mod <ident>;` item (single-line, no body).
///
/// The visibility is inherited (private) — root-level `mod X;`
/// declarations don't need `pub` because the root file's `use` items
/// bring the symbols into scope without re-exporting the module itself.
fn build_mod_item(ident: &str) -> Item {
    Item::Mod(ItemMod {
        attrs: Vec::new(),
        vis: Visibility::Inherited,
        unsafety: None,
        mod_token: Default::default(),
        ident: Ident::new(ident, ProcSpan::call_site()),
        content: None,
        semi: Some(Default::default()),
    })
}

/// Build a `use <module>::{a, b, c};` (named) or `use <module>::*;`
/// (wildcard) item that brings the imported symbols into scope.
///
/// Returns `None` when both `names` is empty and `wildcard` is `false`
/// — a defensive case that shouldn't occur in practice (the parser
/// requires at least one of them).
fn build_use_item(module: &str, names: &[String], wildcard: bool) -> Option<syn::ItemUse> {
    let module_ident = Ident::new(module, ProcSpan::call_site());
    let tree = if wildcard {
        // `use module::*;`
        syn::UseTree::Glob(syn::UseGlob {
            star_token: Default::default(),
        })
    } else if names.is_empty() {
        return None;
    } else if names.len() == 1 {
        // `use module::name;`
        syn::UseTree::Name(syn::UseName {
            ident: Ident::new(&names[0], ProcSpan::call_site()),
        })
    } else {
        // `use module::{a, b, c};`
        let mut paths: syn::punctuated::Punctuated<syn::UseTree, syn::Token![,]> =
            syn::punctuated::Punctuated::new();
        for n in names {
            paths.push_value(syn::UseTree::Name(syn::UseName {
                ident: Ident::new(n, ProcSpan::call_site()),
            }));
            paths.push_punct(Default::default());
        }
        // Trailing punct is fine — prettyplease normalises.
        syn::UseTree::Group(syn::UseGroup {
            brace_token: Default::default(),
            items: paths,
        })
    };
    Some(syn::ItemUse {
        attrs: Vec::new(),
        vis: Visibility::Inherited,
        use_token: Default::default(),
        leading_colon: None,
        semi_token: Default::default(),
        tree: syn::UseTree::Path(syn::UsePath {
            ident: module_ident,
            colon2_token: Default::default(),
            tree: Box::new(tree),
        }),
    })
}

/// Generate multi-file Rust output for a multi-module Buff program (T8).
///
/// `root_decls` are the declarations of the entry-point Buff file.
/// `modules` is the flat list of transitively-reachable imported modules
/// (de-duplicated by the pipeline on `from_path` so each module appears
/// exactly once even if imported from multiple files).
///
/// The function:
///
/// 1. Builds the ROOT source by:
///    - Prepending `mod X;` items for each module (in `modules` order).
///    - Prepending `use X::{...};` items for each ES6 import in the
///      root (in source order).
///    - Lowering the non-import root decls via [`RustCodegen::generate`].
/// 2. Builds each MODULE source via [`generate_module_source`] (filters
///    out imports, lowers the rest).
/// 3. Aggregates extern_crates across root + all modules.
///
/// # Errors
///
/// Propagates [`CodegenError`] from any per-module lowering failure.
pub fn generate_multi_crate(
    root_decls: &[Decl],
    modules: &[ParsedModule],
) -> Result<MultiCrateOutput, CodegenError> {
    // 1. Lower each module. The order is determined by the BTreeMap key
    //    (sanitised ident) at storage time so the output is deterministic
    //    regardless of `modules` slice order.
    let mut module_sources: BTreeMap<String, String> = BTreeMap::new();
    let mut aggregated_extern_crates: BTreeSet<String> = BTreeSet::new();
    // Track idents we've already emitted so a duplicate from_path
    // (defensive — the pipeline de-dupes on from_path, but two distinct
    // paths could sanitise to the same ident) is detected with a clear
    // error rather than silently overwriting.
    let mut seen_idents: BTreeSet<String> = BTreeSet::new();
    for m in modules {
        if !seen_idents.insert(m.ident.clone()) {
            return Err(multi_crate_error(format!(
                "two distinct module paths sanitised to the same Rust ident `{}` \
                 — rename one of the source files to avoid the collision",
                m.ident
            )));
        }
        let (src, ext) = generate_module_source(&m.decls)?;
        // The previous insert into seen_idents proved the key is absent
        // from module_sources too; insert is guaranteed unique.
        module_sources.insert(m.ident.clone(), src);
        aggregated_extern_crates.extend(ext);
    }

    // 2. Lower the root. Filter out imports + reexports (they become
    //    mod/use items below); lower the rest via the standard codegen.
    let filtered_root: Vec<Decl> = root_decls
        .iter()
        .filter(|d| !is_module_graph_decl(d))
        .cloned()
        .collect();
    let mut root_codegen = RustCodegen::new();
    let mut root_file = root_codegen.generate(&filtered_root)?;
    aggregated_extern_crates.extend(root_codegen.extern_crates().clone());

    // 3. Build mod + use items and prepend them to the root file.
    let mut prefix_items: Vec<Item> = Vec::new();

    // mod X; for each module (deterministic BTreeMap order).
    for ident in module_sources.keys() {
        prefix_items.push(build_mod_item(ident));
    }

    // use X::{...}; for each ES6 import in the root (source order).
    for (from_path, names, wildcard) in collect_es6_imports(root_decls) {
        let module_ident = module_ident_from_path(from_path);
        // Only emit a use item if the imported module is actually in
        // our `modules` set. If the user wrote `import { foo } from
        // "./missing.buff"` and the pipeline didn't supply a parsed
        // module for it (e.g. file not found), the `mod X;` would
        // fail at rustc time anyway — but we don't want to emit a
        // dangling `use X::foo;` here. The pipeline surfaces the
        // missing-file error before reaching this point.
        if !module_sources.contains_key(&module_ident) {
            return Err(multi_crate_error(format!(
                "import `from {from_path:?}` resolves to Rust ident `{module_ident}` \
                 but no matching parsed module was supplied — the pipeline must \
                 resolve every `from \"...\"` path before calling generate_multi_crate"
            )));
        }
        if let Some(use_item) = build_use_item(&module_ident, &names, wildcard) {
            prefix_items.push(Item::Use(use_item));
        }
    }

    // Prepend prefix_items to the root file's items (mod + use come
    // first, then the user's decls).
    let mut combined = prefix_items;
    combined.append(&mut root_file.items);
    root_file.items = combined;

    let root_source = format(&root_file);

    Ok(MultiCrateOutput {
        root_source,
        modules: module_sources,
        extern_crates: aggregated_extern_crates,
    })
}

/// Build a [`CodegenError`] carrying the E1300 multi-crate emission
/// error code (T8). The span is `dummy()` because the error is a
/// structural / module-graph concern, not tied to a single source span.
fn multi_crate_error(message: String) -> CodegenError {
    CodegenError::new(Diagnostic::error(message, BuffSpan::dummy()))
}

#[cfg(test)]
mod tests {
    use super::*;
    use buff_lang_ast::{common::Ident, ImportDecl};
    use buff_lang_error::Span;

    #[test]
    fn uses_multi_crate_false_for_no_imports() {
        let decls: Vec<Decl> = vec![];
        assert!(!uses_multi_crate(&decls));
    }

    #[test]
    fn uses_multi_crate_false_for_legacy_import() {
        // Legacy form: import a.b.c (no from_path).
        let decls = vec![Decl::ImportDecl(ImportDecl {
            path: vec![Ident::new("a", Span::dummy())],
            imports: vec![],
            alias: None,
            from_path: None,
            wildcard: false,
            span: Span::dummy(),
        })];
        assert!(
            !uses_multi_crate(&decls),
            "legacy import should NOT activate multi-crate"
        );
    }

    #[test]
    fn uses_multi_crate_true_for_es6_import() {
        let decls = vec![Decl::ImportDecl(ImportDecl {
            path: vec![],
            imports: vec![],
            alias: None,
            from_path: Some("./greet.buff".to_string()),
            wildcard: false,
            span: Span::dummy(),
        })];
        assert!(uses_multi_crate(&decls));
    }

    #[test]
    fn module_ident_strips_path_and_extension() {
        assert_eq!(module_ident_from_path("./greet.buff"), "greet");
        assert_eq!(module_ident_from_path("greet.buff"), "greet");
        assert_eq!(module_ident_from_path("./utils/helpers.buff"), "helpers");
        assert_eq!(module_ident_from_path("../sibling.buff"), "sibling");
        assert_eq!(
            module_ident_from_path("../../deeply/nested/file.buff"),
            "file"
        );
    }

    #[test]
    fn module_ident_handles_digit_leading_stem() {
        assert_eq!(module_ident_from_path("./123.buff"), "m123");
        assert_eq!(module_ident_from_path("./1st.buff"), "m1st");
    }

    #[test]
    fn module_ident_replaces_non_ident_chars() {
        assert_eq!(module_ident_from_path("./my-mod.buff"), "my_mod");
        assert_eq!(module_ident_from_path("./my.mod.buff"), "my");
        assert_eq!(module_ident_from_path("./foo bar.buff"), "foo_bar");
    }

    #[test]
    fn module_ident_fallback_for_empty() {
        assert_eq!(module_ident_from_path("./.buff"), "module");
        assert_eq!(module_ident_from_path(""), "module");
    }

    #[test]
    fn module_ident_handles_double_extension() {
        // `greet.v2.buff` → stem is `greet.v2` (rsplit_once takes the
        // last `.`), then non-ident chars are replaced.
        assert_eq!(module_ident_from_path("./greet.v2.buff"), "greet_v2");
    }

    #[test]
    fn generate_module_source_skips_imports() {
        // A trivial module with one import + one fn. The import should
        // be filtered; only the fn should appear in the output.
        let decls = vec![
            Decl::ImportDecl(ImportDecl {
                path: vec![],
                imports: vec![],
                alias: None,
                from_path: Some("./other.buff".to_string()),
                wildcard: false,
                span: Span::dummy(),
            }),
            Decl::FuncDecl(buff_lang_ast::FuncDecl {
                name: Ident::new("helper", Span::dummy()),
                params: vec![],
                return_type: None,
                body: buff_lang_ast::common::Block::empty(Span::dummy()),
                is_async: false,
                is_unsafe: false,
                is_extern: false,
                attributes: vec![],
                type_params: vec![],
                span: Span::dummy(),
            }),
        ];
        let (src, _ext) = generate_module_source(&decls).expect("module codegen ok");
        assert!(
            src.contains("fn helper"),
            "expected fn helper in module output; got:\n{src}"
        );
        assert!(
            !src.contains("import"),
            "import decl should be filtered out; got:\n{src}"
        );
    }

    #[test]
    fn generate_multi_crate_end_to_end_minimal() {
        // Two-module program: root imports greet from ./greet.buff.
        // Synthetic decls — we don't run the parser, just construct
        // the AST directly.
        let root_decls = vec![
            Decl::ImportDecl(ImportDecl {
                path: vec![],
                imports: vec![Ident::new("greet", Span::dummy())],
                alias: None,
                from_path: Some("./greet.buff".to_string()),
                wildcard: false,
                span: Span::dummy(),
            }),
            Decl::FuncDecl(buff_lang_ast::FuncDecl {
                name: Ident::new("main", Span::dummy()),
                params: vec![],
                return_type: None,
                body: buff_lang_ast::common::Block::empty(Span::dummy()),
                is_async: false,
                is_unsafe: false,
                is_extern: false,
                attributes: vec![],
                type_params: vec![],
                span: Span::dummy(),
            }),
        ];
        let greet_decls = vec![Decl::FuncDecl(buff_lang_ast::FuncDecl {
            name: Ident::new("greet", Span::dummy()),
            params: vec![],
            return_type: None,
            body: buff_lang_ast::common::Block::empty(Span::dummy()),
            is_async: false,
            is_unsafe: false,
            is_extern: false,
            attributes: vec![],
            type_params: vec![],
            span: Span::dummy(),
        })];
        let modules = vec![ParsedModule {
            ident: "greet".to_string(),
            from_path: "./greet.buff".to_string(),
            decls: greet_decls,
        }];
        let out = generate_multi_crate(&root_decls, &modules).expect("multi-crate ok");

        // Root has `mod greet;` + `use greet::greet;` + `fn main`.
        assert!(
            out.root_source.contains("mod greet"),
            "expected `mod greet;` in root; got:\n{}",
            out.root_source
        );
        assert!(
            out.root_source.contains("use greet::greet"),
            "expected `use greet::greet;` in root; got:\n{}",
            out.root_source
        );
        assert!(
            out.root_source.contains("fn main"),
            "expected `fn main` in root; got:\n{}",
            out.root_source
        );
        // The greet module is emitted as a sibling file containing `fn greet`.
        let greet_src = out.modules.get("greet").expect("greet module emitted");
        assert!(
            greet_src.contains("fn greet"),
            "expected `fn greet` in greet.rs; got:\n{}",
            greet_src
        );
        // The root should NOT contain the greet fn body (it's in the module).
        assert!(
            !out.root_source.contains("fn greet"),
            "greet fn should NOT be in root (it's in greet.rs); got:\n{}",
            out.root_source
        );
    }

    #[test]
    fn generate_multi_crate_wildcard_import_emits_glob() {
        let root_decls = vec![Decl::ImportDecl(ImportDecl {
            path: vec![],
            imports: vec![],
            alias: None,
            from_path: Some("./utils.buff".to_string()),
            wildcard: true,
            span: Span::dummy(),
        })];
        let modules = vec![ParsedModule {
            ident: "utils".to_string(),
            from_path: "./utils.buff".to_string(),
            decls: vec![],
        }];
        let out = generate_multi_crate(&root_decls, &modules).expect("multi-crate ok");
        assert!(
            out.root_source.contains("use utils::*"),
            "expected `use utils::*;` for wildcard import; got:\n{}",
            out.root_source
        );
    }

    #[test]
    fn generate_multi_crate_errors_on_missing_module() {
        // Root imports from "./missing.buff" but no ParsedModule is supplied.
        let root_decls = vec![Decl::ImportDecl(ImportDecl {
            path: vec![],
            imports: vec![Ident::new("foo", Span::dummy())],
            alias: None,
            from_path: Some("./missing.buff".to_string()),
            wildcard: false,
            span: Span::dummy(),
        })];
        let result = generate_multi_crate(&root_decls, &[]);
        assert!(
            result.is_err(),
            "expected error when import has no matching parsed module"
        );
        let err = result.unwrap_err();
        assert!(
            err.diagnostic.message.contains("missing.buff"),
            "error should reference the missing path; got: {}",
            err.diagnostic.message
        );
    }

    #[test]
    fn generate_multi_crate_errors_on_ident_collision() {
        // Two modules with the same sanitised ident.
        let root_decls: Vec<Decl> = vec![];
        let modules = vec![
            ParsedModule {
                ident: "greet".to_string(),
                from_path: "./greet.buff".to_string(),
                decls: vec![],
            },
            ParsedModule {
                ident: "greet".to_string(),
                from_path: "./other/greet.buff".to_string(),
                decls: vec![],
            },
        ];
        let result = generate_multi_crate(&root_decls, &modules);
        assert!(
            result.is_err(),
            "expected error when two modules sanitise to the same ident"
        );
    }

    #[test]
    fn generate_multi_crate_aggregates_extern_crates() {
        // Root has `extern crate "chrono"`; module has none. The
        // aggregated set should contain chrono.
        let root_decls = vec![Decl::ExternCrateDecl(buff_lang_ast::ExternCrateDecl {
            name: "chrono".to_string(),
            span: Span::dummy(),
        })];
        let modules = vec![ParsedModule {
            ident: "m1".to_string(),
            from_path: "./m1.buff".to_string(),
            decls: vec![Decl::ExternCrateDecl(buff_lang_ast::ExternCrateDecl {
                name: "rand".to_string(),
                span: Span::dummy(),
            })],
        }];
        let out = generate_multi_crate(&root_decls, &modules).expect("multi-crate ok");
        assert!(out.extern_crates.contains("chrono"));
        assert!(out.extern_crates.contains("rand"));
    }
}
