//! Panic hook — install a `std::panic::set_hook` interceptor that remaps
//! Rust backtraces to Buff source locations.
//!
//! # Lifecycle
//!
//! 1. **Codegen time**: [`build_source_map`](crate::build_source_map) +
//!    [`serialize_to_string`](crate::format::serialize_to_string) write a
//!    `.buffmap` sidecar next to the compiled binary.
//! 2. **Runtime init**: [`install_panic_hook`] is called once when the
//!    Buff runtime initializes. It looks up the `.buffmap` path from
//!    `BUFF_MAP_PATH` env var (falling back to `<current_exe>.buffmap`).
//! 3. **On panic**: the hook walks the Rust backtrace, remaps each frame
//!    to its Buff source location via [`remap_panic_backtrace`], and
//!    prints the Buff trace to stderr. The full Rust trace is preserved
//!    as an escape hatch — printed AFTER the Buff trace when
//!    `RUST_BACKTRACE=1` is set.
//!
//! # Why not embed the source map in the binary?
//!
//! Two reasons:
//!
//! 1. **Sidecar files are debuggable**: users can `cat foo.buffmap` to
//!    see the mappings, post-process them, share them with bug reports.
//! 2. **No codegen bloat**: the Rust source generated by Buff stays
//!    focused on the program logic; debug info lives in its own file.
//!
//! # `RUST_BACKTRACE=1` escape hatch
//!
//! The Buff trace is ALWAYS printed (the hook is installed transparently
//! at runtime init). When `RUST_BACKTRACE=1` is also set, the FULL Rust
//! backtrace is additionally printed AFTER the Buff trace so advanced
//! users can drill into Rust internals when debugging interop issues.

use std::backtrace::Backtrace;
use std::io::Write;
use std::path::PathBuf;
use std::sync::OnceLock;

use crate::{format, SourceMap};

/// Process-global cache of the loaded `.buffmap` (loaded once on first
/// panic). `None` after [`install_panic_hook`] runs means no `.buffmap`
/// was found — the hook falls back to the default Rust panic message.
static BUFF_MAP: OnceLock<Option<SourceMap>> = OnceLock::new();

/// Install the Buff panic hook.
///
/// Looks up the `.buffmap` path from the `BUFF_MAP_PATH` env var first,
/// then falls back to `<current_exe>.buffmap`. When neither exists the
/// hook is still installed but does nothing (defers to the default Rust
/// panic message + backtrace).
///
/// Calling this more than once is a no-op — `std::panic::set_hook`
/// overwrites the previous hook, and the source map is cached in a
/// [`OnceLock`] so repeated calls return cheaply.
pub fn install_panic_hook() {
    let map_path = resolve_buff_map_path();
    let map = map_path
        .as_ref()
        .and_then(|p| format::read_from_file(p).ok());
    let _ = BUFF_MAP.set(map);
    std::panic::set_hook(Box::new(buff_panic_handler));
}

/// Resolve the `.buffmap` file path from `BUFF_MAP_PATH` or
/// `<current_exe>.buffmap`.
///
/// Returns `None` when neither path exists on disk. The path is NOT
/// validated as a real `.buffmap` file here — that's deferred to the
/// `format::read_from_file` call inside [`install_panic_hook`].
pub fn resolve_buff_map_path() -> Option<PathBuf> {
    if let Ok(path_str) = std::env::var("BUFF_MAP_PATH") {
        let path = PathBuf::from(path_str);
        if path.exists() {
            return Some(path);
        }
    }
    let exe = std::env::current_exe().ok()?;
    let mut buffmap = exe.clone();
    buffmap.set_extension("buffmap");
    if buffmap.exists() {
        Some(buffmap)
    } else {
        None
    }
}

/// The actual panic handler installed by [`install_panic_hook`].
///
/// Renders:
///
/// 1. The standard `thread '<name>' panicked at <msg>` line + location,
///    with the Rust source path translated to the Buff source path when
///    a mapping exists.
/// 2. A `Buff stack trace:` section with each Rust frame remapped to
///    its Buff source location (when a mapping exists).
/// 3. When `RUST_BACKTRACE=1` is set, the full Rust backtrace printed
///    AFTER the Buff trace (escape hatch preserved).
fn buff_panic_handler(info: &std::panic::PanicHookInfo<'_>) {
    let location = info.location();
    let msg = info.payload();
    let payload_str = if let Some(s) = msg.downcast_ref::<&'static str>() {
        (*s).to_string()
    } else if let Some(s) = msg.downcast_ref::<String>() {
        s.clone()
    } else {
        "Box<dyn Any>".to_string()
    };
    let map = BUFF_MAP.get().and_then(|opt| opt.as_ref());

    let mut stderr = std::io::stderr().lock();
    let thread_name = std::thread::current()
        .name()
        .map(String::from)
        .unwrap_or_else(|| "<unnamed>".to_string());
    let _ = writeln!(stderr, "thread '{thread_name}' panicked at {payload_str}");

    if let (Some(loc), Some(map)) = (location, map) {
        let rust_file = loc.file();
        let rust_line = loc.line();
        if let Some(buff_loc) = map.lookup_buff(rust_line as usize) {
            let buff_path = map
                .buff_file
                .as_ref()
                .map(|p| p.to_string_lossy().into_owned())
                .unwrap_or_else(|| rust_file.to_string());
            let _ = writeln!(
                stderr,
                "  --> {}:{}:{}",
                buff_path, buff_loc.line, buff_loc.col
            );
        } else {
            let _ = writeln!(stderr, "  --> {rust_file}:{rust_line}:{}", loc.column());
        }
    } else if let Some(loc) = location {
        let _ = writeln!(
            stderr,
            "  --> {}:{}:{}",
            loc.file(),
            loc.line(),
            loc.column()
        );
    }

    let trace = remap_panic_backtrace(map);
    if !trace.frames.is_empty() {
        let _ = writeln!(stderr, "\nBuff stack trace:");
        for (idx, frame) in trace.frames.iter().enumerate() {
            let name = frame.buff_name.as_deref().unwrap_or("<anonymous>");
            let _ = writeln!(
                stderr,
                "  {}: {} ({}:{}:{})",
                idx, name, trace.buff_file_display, frame.buff_line, frame.buff_col
            );
        }
    }

    if std::env::var("RUST_BACKTRACE")
        .map(|v| v == "1")
        .unwrap_or(false)
    {
        let _ = writeln!(stderr, "\nFull Rust backtrace (RUST_BACKTRACE=1):");
        let _ = writeln!(stderr, "{}", std::backtrace::Backtrace::force_capture());
    }
}

/// A remapped Buff stack trace.
///
/// Built by [`remap_panic_backtrace`] from a Rust [`Backtrace`] snapshot
/// plus the loaded [`SourceMap`]. Frames without a Buff mapping are
/// dropped — only Buff-source frames appear in the trace.
#[derive(Debug, Clone, Default)]
pub struct BuffTrace {
    pub frames: Vec<BuffTraceFrame>,
    pub buff_file_display: String,
}

/// One frame in a [`BuffTrace`].
#[derive(Debug, Clone)]
pub struct BuffTraceFrame {
    pub buff_line: usize,
    pub buff_col: usize,
    pub buff_name: Option<String>,
    pub rust_line: usize,
}

/// Remap a Rust backtrace into a Buff stack trace.
///
/// When `map` is `None` or empty, returns an empty [`BuffTrace`] (the
/// caller's `RUST_BACKTRACE=1` escape hatch still surfaces the raw Rust
/// trace via the panic handler's escape-hatch branch).
///
/// The current implementation walks a fresh [`Backtrace::capture`]
/// snapshot. A future enhancement could accept a pre-captured backtrace
/// for `buff backtrace`-style offline use.
pub fn remap_panic_backtrace(map: Option<&SourceMap>) -> BuffTrace {
    let Some(map) = map else {
        return BuffTrace::default();
    };
    if map.is_empty() {
        return BuffTrace::default();
    }
    let backtrace = Backtrace::capture();
    let trace_str = backtrace.to_string();
    let buff_file_display = map
        .buff_file
        .as_ref()
        .map(|p| p.to_string_lossy().into_owned())
        .unwrap_or_else(|| "<unknown>".to_string());

    let mut frames = Vec::new();
    for rust_line in extract_rust_lines_from_backtrace(&trace_str) {
        if let Some(loc) = map.lookup_buff(rust_line) {
            frames.push(BuffTraceFrame {
                buff_line: loc.line,
                buff_col: loc.col,
                buff_name: loc.name.clone(),
                rust_line,
            });
        }
    }
    BuffTrace {
        frames,
        buff_file_display,
    }
}

/// Parse the backtrace string and extract the Rust line numbers.
///
/// Looks for the pattern `<file>:<line>` where `<file>` ends with `.rs`.
/// The backtrace crate formats frames with file paths + line numbers;
/// this helper extracts just the line numbers from Rust-source frames.
fn extract_rust_lines_from_backtrace(backtrace_str: &str) -> Vec<usize> {
    let mut lines = Vec::new();
    for line in backtrace_str.lines() {
        if let Some(rust_line) = extract_rust_line_from_frame(line) {
            lines.push(rust_line);
        }
    }
    lines
}

/// Try to extract a Rust line number from a single backtrace frame line.
///
/// Matches patterns like `<...>.rs:LINE` or `<...>.rs:LINE:COL`. Returns
/// `None` for non-Rust frames (e.g. system libraries without `.rs`
/// extensions).
fn extract_rust_line_from_frame(line: &str) -> Option<usize> {
    let rs_idx = line.rfind(".rs")?;
    let after_rs = &line[rs_idx + ".rs".len()..];
    let rest = after_rs.strip_prefix(':')?;
    let line_str: String = rest.chars().take_while(|c| c.is_ascii_digit()).collect();
    if line_str.is_empty() {
        return None;
    }
    line_str.parse::<usize>().ok()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::{FunctionAnchor, SourceMap};
    use buff_lang_error::{SourceId, Span};

    #[test]
    fn extract_rust_line_finds_rs_line() {
        assert_eq!(
            extract_rust_line_from_frame("   1: foo\n             at /tmp/bar.rs:42:7"),
            Some(42)
        );
        assert_eq!(
            extract_rust_line_from_frame("   2: baz\n             at C:\\proj\\x.rs:13:5"),
            Some(13)
        );
    }

    #[test]
    fn extract_rust_line_returns_none_for_non_rs() {
        assert_eq!(
            extract_rust_line_from_frame("   1: foo\n             at libc.so.6"),
            None
        );
        assert_eq!(
            extract_rust_line_from_frame("note: run with RUST_BACKTRACE=1"),
            None
        );
    }

    #[test]
    fn extract_rust_line_returns_none_when_no_line_number() {
        assert_eq!(extract_rust_line_from_frame("at foo.rs"), None);
        assert_eq!(extract_rust_line_from_frame("at foo.rs:"), None);
    }

    #[test]
    fn extract_rust_lines_from_backtrace_multiple() {
        let trace = "stack backtrace:\n\
   0: foo\n      at a.rs:1:1\n\
   1: bar\n      at b.rs:2:1\n\
   2: libc\n      at <unknown>\n";
        let lines = extract_rust_lines_from_backtrace(trace);
        assert_eq!(lines, vec![1, 2]);
    }

    #[test]
    fn remap_panic_backtrace_returns_empty_when_map_none() {
        let trace = remap_panic_backtrace(None);
        assert!(trace.frames.is_empty());
    }

    #[test]
    fn remap_panic_backtrace_returns_empty_when_map_empty() {
        let map = SourceMap::new();
        let trace = remap_panic_backtrace(Some(&map));
        assert!(trace.frames.is_empty());
    }

    #[test]
    fn buff_trace_frame_carries_buff_line_and_name() {
        let span = Span::new(10, 50, SourceId(0));
        let anchor = FunctionAnchor {
            name: "helper".to_string(),
            buff_span: span,
            buff_line: 1,
            buff_col: 1,
            rust_start_line: 3,
            rust_end_line: 5,
            buff_location: Some(crate::BuffLocation {
                line: 1,
                col: 1,
                span,
                name: Some("helper".to_string()),
            }),
        };
        let frame = BuffTraceFrame {
            buff_line: anchor.buff_line,
            buff_col: anchor.buff_col,
            buff_name: Some(anchor.name.clone()),
            rust_line: 3,
        };
        assert_eq!(frame.buff_name.as_deref(), Some("helper"));
        assert_eq!(frame.buff_line, 1);
    }

    #[test]
    fn resolve_buff_map_path_returns_none_for_missing_paths() {
        std::env::remove_var("BUFF_MAP_PATH");
        let exe_path = std::env::current_exe().unwrap_or_else(|_| PathBuf::from("__nonexistent__"));
        let mut buffmap = exe_path.clone();
        buffmap.set_extension("buffmap");
        let _ = std::fs::remove_file(&buffmap);
        let result = resolve_buff_map_path();
        assert!(
            result.is_none() || result.as_ref().map(|p| p.exists()).unwrap_or(false),
            "should return None or an existing path, got: {result:?}"
        );
    }

    #[test]
    fn resolve_buff_map_path_reads_env_var_when_file_exists() {
        let tmp =
            std::env::temp_dir().join(format!("buff-test-buffmap-{}.buffmap", std::process::id()));
        std::fs::write(&tmp, "{}").unwrap_or_else(|e| panic!("write {e}"));
        std::env::set_var("BUFF_MAP_PATH", &tmp);
        let result = resolve_buff_map_path();
        std::env::remove_var("BUFF_MAP_PATH");
        let _ = std::fs::remove_file(&tmp);
        assert_eq!(result, Some(tmp));
    }
}
