// T26 example: scan a fake project for vulnerable dependencies.
//
// Demonstrates the `Audit.scan(path)` surface on a temporary
// project root containing a Cargo.lock with a known-vulnerable
// chrono 0.4.19 entry. Prints the advisory IDs that fired +
// the detailed remediation hints via `Audit.scan_with_detail(path)`.

use buff_audit::{scan, scan_with_detail};

fn main() {
    let tmp = std::env::temp_dir().join(format!("buff-audit-example-scan-{}", std::process::id()));
    let _ = std::fs::remove_dir_all(&tmp);
    std::fs::create_dir_all(&tmp).expect("mkdir");

    let cargo_lock = tmp.join("Cargo.lock");
    std::fs::write(
        &cargo_lock,
        r#"# This file is automatically @generated by Cargo.
[[package]]
name = "chrono"
version = "0.4.19"
source = "registry+https://github.com/rust-lang/crates.io-index"
"#,
    )
    .expect("write Cargo.lock");

    let hits = scan(&tmp).expect("scan");
    println!("scan({}) -> {} hits", tmp.display(), hits.len());
    for id in &hits {
        println!("  - {}", id);
    }

    let details = scan_with_detail(&tmp).expect("scan_with_detail");
    println!();
    println!("detailed:");
    for hit in &details {
        println!(
            "  - {} (package={}, patched={})",
            hit.id, hit.package, hit.patched
        );
    }

    let _ = std::fs::remove_dir_all(&tmp);
}
