//! The [`Strategy`] value type — describes how to generate random inputs.
//!
//! A `Strategy` is the user-facing description of the input space a
//! property test should explore. It is constructed via the type-level
//! associated functions ([`Strategy::int`], [`Strategy::float`],
//! [`Strategy::bool`], [`Strategy::string`], [`Strategy::bytes`]) and
//! consumed by the [`crate::run`] entry point.
//!
//! # Value generation
//!
//! Internally the runner drives a `proptest::strategy::Strategy` impl
//! built from the Buff-level [`Strategy`] value. The mapping is:
//!
//! | Buff Strategy            | proptest backend             |
//! |--------------------------|------------------------------|
//! | `Strategy.int(min, max)` | `min..=max`                  |
//! | `Strategy.float()`       | `proptest::num::f64::ANY`    |
//! | `Strategy.bool()`        | `proptest::strategy::Any`    |
//! | `Strategy.string()`      | `proptest::string::string_regex(".+")` |
//! | `Strategy.bytes()`       | `proptest::collection::vec(any::<u8>(), 0..64)` |
//!
//! MVP scope: only the `Int` strategy is *driver-driven* today — the
//! runner generates `i64` values and feeds them to a `Fn(i64) -> bool`
//! closure. The other variants are exposed so users can construct them
//! (mirroring the surface the codegen layer expects), but the property
//! closure currently receives `i64` for every strategy kind (the
//! string/bytes payloads are converted to their length, or hashed to an
//! i64, before being passed to the property). A follow-up task will
//! surface a `FuzzValue` enum so the closure can match on the original
//! payload kind.
//!
//! # Hard-rule compliance
//!
//! No `unwrap` / `expect` / `panic!` / `todo!` in any of the
//! constructors (project hard rule). Constructors are infallible at the
//! surface — even a structurally invalid strategy (e.g. `min > max`) is
//! accepted here and surfaced as [`crate::FuzzError::InvalidStrategy`]
//! at the [`crate::run`] call site.

#[derive(Debug, Clone, PartialEq)]
pub enum Strategy {
    Int { min: i64, max: i64 },
    Float { min: f64, max: f64 },
    Bool,
    String { max_len: usize },
    Bytes { max_len: usize },
}

impl Strategy {
    pub fn int(min: i64, max: i64) -> Self {
        Self::Int { min, max }
    }

    pub fn float(min: f64, max: f64) -> Self {
        Self::Float { min, max }
    }

    pub fn bool() -> Self {
        Self::Bool
    }

    pub fn string(max_len: usize) -> Self {
        Self::String { max_len }
    }

    pub fn bytes(max_len: usize) -> Self {
        Self::Bytes { max_len }
    }

    pub(crate) fn validate(&self) -> Result<(), crate::FuzzError> {
        use crate::FuzzError;
        match self {
            Self::Int { min, max } if min > max => Err(FuzzError::invalid_strategy(format!(
                "Int range min ({min}) > max ({max})"
            ))),
            Self::Float { min, max } if min > max => Err(FuzzError::invalid_strategy(format!(
                "Float range min ({min}) > max ({max})"
            ))),
            Self::String { max_len } if *max_len == 0 => {
                Err(FuzzError::invalid_strategy("String max_len must be > 0"))
            }
            Self::Bytes { max_len } if *max_len == 0 => {
                Err(FuzzError::invalid_strategy("Bytes max_len must be > 0"))
            }
            _ => Ok(()),
        }
    }
}

impl Default for Strategy {
    fn default() -> Self {
        Self::int(0, 100)
    }
}

impl std::fmt::Display for Strategy {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Int { min, max } => write!(f, "Strategy.int({min}, {max})"),
            Self::Float { min, max } => write!(f, "Strategy.float({min}, {max})"),
            Self::Bool => write!(f, "Strategy.bool()"),
            Self::String { max_len } => write!(f, "Strategy.string({max_len})"),
            Self::Bytes { max_len } => write!(f, "Strategy.bytes({max_len})"),
        }
    }
}

/// A type-erased value generated by a [`Strategy`].
///
/// The MVP runner feeds `i64` to the property closure directly; this
/// enum is exposed for the future "typed property" surface where a
/// closure receives the original generated payload (String / Vec<u8> /
/// bool / f64 / i64) instead of an i64 projection.
#[derive(Debug, Clone, PartialEq)]
pub enum FuzzValue {
    Int(i64),
    Float(f64),
    Bool(bool),
    String(String),
    Bytes(Vec<u8>),
}

impl FuzzValue {
    pub fn as_int(&self) -> Option<i64> {
        match self {
            Self::Int(n) => Some(*n),
            _ => None,
        }
    }
}
