//! Project scaffolding — templates and validation shared by `buff new` and
//! `buff init`.
//!
//! Templates are plain strings with a single `{name}` placeholder substituted
//! by [`render_template`]. They are deliberately simple (no TPL engine dep):
//! the v0.1 generated project is four small files, and a `str::replace` call
//! keeps the dependency surface minimal.
//!
//! [`validate_project_name`] enforces the same identifier rules the lexer will
//! later apply to symbols, plus a check against the 25 reserved keywords (see
//! `crates/buff-lang-lexer/src/token.rs`).

/// Reserved Buff keywords (must match the lexer's keyword table).
///
/// Sourcing this as a static array here (instead of importing from the lexer)
/// keeps `buff new` / `buff init` decoupled from lexer internals — the keyword
/// list is small and stable since v0.1.
pub const KEYWORDS: &[&str] = &[
    "func", "let", "mut", "struct", "enum", "trait", "type", "if", "else", "for", "return",
    "break", "continue", "in", "match", "async", "spawn", "import", "export", "from", "as", "true",
    "false", "extern", "unsafe",
];

/// `buff.toml` manifest template.
///
/// `{name}` is replaced with the project name. The `edition` field tracks the
/// Buff language edition (semver-ish); v0.1 emits `"0.1"`.
pub const BUFF_TOML_TEMPLATE: &str = r#"[package]
name = "{name}"
version = "0.1.0"
edition = "0.1"
"#;

/// T0-C1: v2 manifest template emitted by `buff new --template <name>`
/// (Buff SDK 2.0). Carries `edition = "2026"` + `stability = "experimental"`
/// + the v2 section skeletons so newly-scaffolded projects opt into v2.
pub const BUFF_TOML_V2_TEMPLATE: &str = r#"[package]
name = "{name}"
version = "0.1.0"
edition = "2026"
stability = "experimental"

[features]
default = []

[lints]
clippy = "deny"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
"#;

/// `src/main.buff` entry-point template.
///
/// `{name}` is referenced in a leading comment. The body is the canonical v0.1
/// "Hello, Buff!" program and is runnable via `buff run src/main.buff`.
pub const MAIN_BUFF_TEMPLATE: &str = r#"// {name} - generated by `buff new`
func main():
    print("Hello, Buff!")
"#;

/// `.gitignore` template emitted into the project root.
///
/// Ignores the cargo `target/` tree, the per-project `buff.lock`, and any
/// stray generated `.rs` files (the transpiler writes them next to the source
/// — keeping them out of VCS is the user's signal that they're build artifacts).
pub const GITIGNORE_TEMPLATE: &str = r#"target/
buff.lock
*.rs
.env
"#;

/// T0-C1: shared `tests/test_hello.buff` emitted by every template.
/// Mirrors the canonical "first test" pattern: a single `@test` fn that
/// asserts a trivial equality. Templates can add more tests later.
pub const TEST_HELLO_BUFF_TEMPLATE: &str = r#"// Smoke test for {name}.
// Run with: buff test tests/test_hello.buff

@test
fn test_greeting():
    let expected = "Hello, " + "world" + "!"
    assert(expected == "Hello, world!")
"#;

/// T0-C1: shared `examples/hello.buff` emitted by every template.
/// A minimal `func main(): print(...)` runnable via `buff run examples/hello.buff`.
pub const EXAMPLE_HELLO_BUFF_TEMPLATE: &str = r#"// Example for {name}.
// Run with: buff run examples/hello.buff

func main():
    print("Hello from {name}!")
"#;

/// T0-C1: shared `.github/workflows/ci.yml` emitted by every template.
/// 3-OS matrix (ubuntu/windows/macos), Rust 1.95.0 (matches repo pin),
/// runs `buff fmt --check` + `buff check -D` + `buff test`. Mirrors the
/// CI the buff-lang org runs on its own crates.
pub const CI_YML_TEMPLATE: &str = r#"name: CI

on:
  push:
    branches: [main, master]
  pull_request:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.95.0
      - name: Install Buff
        run: cargo install --git https://github.com/buff-lang/buff buff-lang-cli
      - name: Format check
        run: buff fmt --check
      - name: Type check
        run: buff check -D
      - name: Test
        run: buff test
"#;

/// T0-I2: multi-stage `Dockerfile` template (console template only).
/// `builder` image carries rustc + Buff toolchain; `slim` image is the
/// minimal runtime. Mirrors the official `ghcr.io/buff-lang/buff:builder`
/// + `:slim` images shipped in v1.12 (T141).
pub const DOCKERFILE_TEMPLATE: &str = r#"# Multi-stage build for {name}.
FROM ghcr.io/buff-lang/buff:builder AS build
WORKDIR /app
COPY . .
RUN buff build --release

FROM ghcr.io/buff-lang/buff:slim
COPY --from=build /app/target/release/{name} /usr/local/bin/{name}
ENTRYPOINT ["{name}"]
"#;

/// `.env.example` template — documents required env vars without leaking
/// secrets. Emitted by templates that touch env vars (T0-D2).
pub const ENV_EXAMPLE_TEMPLATE: &str = r#"# Copy to .env and fill in real values.
# .env is gitignored.
EXAMPLE_KEY=your-value-here
"#;

/// `README.md` template — minimal usage instructions referencing `buff run`.
pub const README_TEMPLATE: &str = r#"# {name}

Generated by `buff new`.

## Run

```
buff run src/main.buff
```
"#;

/// Validate a project name.
///
/// Rules:
/// - Non-empty.
/// - Starts with an ASCII letter or underscore (not a digit, not unicode).
/// - Subsequent characters are ASCII alphanumeric or underscore.
/// - Not a reserved Buff keyword (see [`KEYWORDS`]).
///
/// # Errors
///
/// Returns a human-readable `String` describing the first violated rule. The
/// message is suitable for direct display to the user via `anyhow::Error::msg`.
pub fn validate_project_name(name: &str) -> Result<(), String> {
    if name.is_empty() {
        return Err("project name cannot be empty".to_string());
    }
    let first = name.chars().next().expect("checked non-empty above");
    if !first.is_ascii_alphabetic() && first != '_' {
        return Err(format!(
            "project name must start with a letter or underscore: `{name}`"
        ));
    }
    if !name.chars().all(|c| c.is_ascii_alphanumeric() || c == '_') {
        return Err(format!(
            "project name contains invalid characters (allowed: a-z, A-Z, 0-9, _): `{name}`"
        ));
    }
    if KEYWORDS.contains(&name) {
        return Err(format!(
            "invalid project name: `{name}` is a reserved Buff keyword"
        ));
    }
    Ok(())
}

/// Substitute the `{name}` placeholder in a template string.
///
/// Uses plain `str::replace`, which replaces *all* occurrences (templates may
/// reference the name multiple times, e.g. the README header and run command).
pub fn render_template(template: &str, name: &str) -> String {
    template.replace("{name}", name)
}

// ===========================================================================
// Template kinds (T112) — `buff new --{lib,server,gpu,workspace}`
// ===========================================================================

/// The kind of project to scaffold via `buff new` / `buff init` (T112).
///
/// Each variant selects a different starter layout (see [`files_for_template`]).
/// [`TemplateKind::Binary`] is the default and matches the original v0.1
/// `buff new` behavior (a runnable `src/main.buff`).
///
/// The `Server` and `Gpu` templates produce *starter* Buff source files that
/// demonstrate the intended async / GPU-dispatch syntax. Running them
/// end-to-end depends on the v1.0 runtime (`tokio` + `wgpu`), so in v0.5 the
/// file is created with reasonable starter content but `buff run` on it is
/// not yet expected to link.
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq)]
pub enum TemplateKind {
    /// A runnable application with `src/main.buff` (default; v0.1 behavior).
    /// Exposed as `--template console` in v2 (T0-C1).
    #[default]
    Binary,
    /// A library module with `src/lib.buff` exporting functions for import.
    Lib,
    /// An async server starter (`async func` + `spawn`); v1.0 runtime to run.
    /// Legacy flag `--server`; not in the v2 7-template list (alias to
    /// console with async demo content for backward compat).
    Server,
    /// A GPU-dispatch starter carrying `@prefer(gpu)` hints; v1.0 runtime to run.
    /// Legacy flag `--gpu`; not in the v2 7-template list (alias to console
    /// with gpu demo content for backward compat).
    Gpu,
    /// A multi-crate workspace layout with member directories under `crates/`.
    Workspace,
    /// T0-C1: `buff-web` + `buff-template` HTTP server scaffold (v1.14+
    /// runtime to actually serve requests; the file is a starter).
    Web,
    /// T0-C1: `buff-ml` + `buff-tensor` project scaffold (v1.15+ runtime
    /// for tensor GPU dispatch; the file is a starter demonstrating the
    /// intended import surface).
    Ml,
    /// T0-C1: `buff-game` + `buff-ecs` project scaffold (v1.16+ runtime
    /// for the game loop; the file is a starter).
    Game,
    /// T0-C1: `buff-pipeline` + `buff-dataframe` ETL scaffold (v1.17+
    /// runtime for the pipeline runner; the file is a starter).
    Pipeline,
}

impl TemplateKind {
    /// Lowercase kebab-name used in user-facing messages and (potentially)
    /// `--template <name>` options. Kept here so the CLI and any future
    /// `--template` value parser share a single source of truth.
    pub fn as_kebab(&self) -> &'static str {
        match self {
            // T0-C1: Binary is exposed as "console" in the v2 template list.
            TemplateKind::Binary => "console",
            TemplateKind::Lib => "lib",
            TemplateKind::Server => "server",
            TemplateKind::Gpu => "gpu",
            TemplateKind::Workspace => "workspace",
            TemplateKind::Web => "web",
            TemplateKind::Ml => "ml",
            TemplateKind::Game => "game",
            TemplateKind::Pipeline => "pipeline",
        }
    }

    /// T0-C1: iterate the 7 user-visible templates. Used by `buff new
    /// --template list` (future) + tests. Excludes the legacy `Server`
    /// and `Gpu` variants (those are reachable only via the `--server`
    /// / `--gpu` flags, not advertised as named templates).
    pub fn user_visible() -> &'static [TemplateKind] {
        &[
            TemplateKind::Binary,
            TemplateKind::Lib,
            TemplateKind::Web,
            TemplateKind::Ml,
            TemplateKind::Game,
            TemplateKind::Pipeline,
            TemplateKind::Workspace,
        ]
    }
}

/// T0-C1: select a [`TemplateKind`] from the `--template <name>` CLI flag.
///
/// Accepts the lowercase kebab-name (see [`TemplateKind::as_kebab`]).
/// Returns `Ok(kind)` on match, `Err` with a helpful message listing the
/// valid names on miss. The legacy `Server` and `Gpu` kinds are reachable
/// here too (`--template server` / `--template gpu`) for completeness,
/// though they're not advertised in the 7-template list.
pub fn template_from_name(name: &str) -> Result<TemplateKind, String> {
    Ok(match name {
        "console" | "binary" => TemplateKind::Binary,
        "lib" => TemplateKind::Lib,
        "server" => TemplateKind::Server,
        "gpu" => TemplateKind::Gpu,
        "workspace" => TemplateKind::Workspace,
        "web" => TemplateKind::Web,
        "ml" => TemplateKind::Ml,
        "game" => TemplateKind::Game,
        "pipeline" => TemplateKind::Pipeline,
        other => {
            let valid: Vec<&'static str> = TemplateKind::user_visible()
                .iter()
                .map(TemplateKind::as_kebab)
                .collect();
            return Err(format!(
                "unknown template `{other}` (valid: {})",
                valid.join(", ")
            ));
        }
    })
}

/// Selects a [`TemplateKind`] from individual CLI boolean flags (T112).
///
/// Maps the `--lib` / `--server` / `--gpu` / `--workspace` flags from the
/// `New` clap variant onto a single [`TemplateKind`]. At most one flag may be
/// `true`; if all are `false`, returns [`TemplateKind::Binary`] (the default
/// — preserves the v0.1 `buff new NAME` behavior with no regressions).
///
/// # Errors
///
/// Returns a human-readable `String` if more than one flag is set.
pub fn template_from_flags(
    lib: bool,
    server: bool,
    gpu: bool,
    workspace: bool,
) -> Result<TemplateKind, String> {
    let set = [lib, server, gpu, workspace].iter().filter(|&&b| b).count();
    if set > 1 {
        return Err(
            "at most one template flag may be set (--lib, --server, --gpu, --workspace)"
                .to_string(),
        );
    }
    Ok(match (lib, server, gpu, workspace) {
        (true, _, _, _) => TemplateKind::Lib,
        (_, true, _, _) => TemplateKind::Server,
        (_, _, true, _) => TemplateKind::Gpu,
        (_, _, _, true) => TemplateKind::Workspace,
        _ => TemplateKind::Binary,
    })
}

// ---------------------------------------------------------------------------
// Per-template content strings
// ---------------------------------------------------------------------------

/// `src/lib.buff` library template (T112 `--lib`).
///
/// Exports two starter functions (`greet`, `add`) with no `func main()` — a
/// library is consumed via `import { greet } from "./name"`, not run directly.
pub const LIB_BUFF_TEMPLATE: &str = r#"// {name} - generated by `buff new --lib`
// Library module. Exported functions are importable by other Buff programs:
//     import { greet } from "./{name}"

export func greet(name):
    print("Hello, " + name + "!")

export func add(a, b):
    return a + b
"#;

/// `src/main.buff` async server template (T112 `--server`).
///
/// Demonstrates the Buff async-without-`await` model: `async func` seeds the
/// call-graph propagation, `spawn` schedules a task, and `.result()` joins.
/// Running requires the Buff `tokio` runtime (v1.0); the file is a starter
/// in v0.5.
pub const SERVER_MAIN_BUFF_TEMPLATE: &str = r#"// {name} - generated by `buff new --server`
// Async server template. Running requires the Buff tokio runtime (v1.0).
// There is NO `await` keyword in Buff — async propagates up the call graph
// automatically, and `.result()` joins a spawned task.

async func handler():
    return "Hello from {name}!"

func main():
    let task = spawn handler()
    let message = task.result()
    print(message)
"#;

/// `src/main.buff` GPU-dispatch template (T112 `--gpu`).
///
/// Carries an `@prefer(gpu)` hint on a compute-style function. Real GPU
/// dispatch (WGSL shader emission + `wgpu` host) arrives in v1.0; the
/// function falls back to CPU automatically when no GPU is present.
pub const GPU_MAIN_BUFF_TEMPLATE: &str = r#"// {name} - generated by `buff new --gpu`
// GPU dispatch template. `@prefer(gpu)` hints the compiler to dispatch the
// annotated function on the GPU when hardware is available (v1.0 runtime).
// When no GPU is present the function runs on CPU — the hint never breaks.

@prefer(gpu)
func compute(a, b):
    return a * b

func main():
    let result = compute(21, 2)
    print(result)
"#;

/// Workspace-root `buff.toml` template (T112 `--workspace`).
///
/// Mirrors Cargo's `[workspace]` manifest shape: a workspace-level manifest
/// lists member crates under `crates/`. The Buff workspace resolver itself
/// is a v1.0 concern; the scaffold produces a structurally-correct starter.
pub const WORKSPACE_BUFF_TOML_TEMPLATE: &str = r#"[workspace]
name = "{name}"
version = "0.1.0"
edition = "0.1"
members = ["crates/core", "crates/utils"]
"#;

/// Workspace member `core/src/main.buff` template — binary crate entry point.
pub const WORKSPACE_CORE_MAIN_BUFF_TEMPLATE: &str = r#"// {name} workspace - core crate entry point
func main():
    print("Hello from {name} core!")
"#;

/// Workspace member `utils/src/lib.buff` template — library crate.
pub const WORKSPACE_UTILS_LIB_BUFF_TEMPLATE: &str = r#"// {name} workspace - utils crate library
export func helper():
    print("utils helper called")
"#;

/// Workspace member `buff.toml` template (shared by `core` and `utils`).
pub const WORKSPACE_MEMBER_BUFF_TOML_TEMPLATE: &str = r#"[package]
name = "{name}"
version = "0.1.0"
edition = "0.1"
"#;

// ===========================================================================
// T0-C1 — New v2 template content (web / ml / game / pipeline)
// ===========================================================================

/// `src/main.buff` for the `web` template (T0-C1).
///
/// Demonstrates the intended `buff-web` HTTP server import surface. The
/// `buff-web` crate arrives with v1.14; the scaffolded file is a starter
/// — running it requires the runtime, but `buff check` accepts the import
/// declaration today (the resolver will resolve once buff-web lands).
pub const WEB_MAIN_BUFF_TEMPLATE: &str = r#"// {name} - generated by `buff new --template web`
// HTTP server starter using buff-web (v1.14 runtime required to run).
// Define routes below; the server listens on port 8080 by default.

import { Server, Route } from "buff-web"

func main():
    let server = Server.new(port: 8080)
    server.route(Route.get("/", handler))
    server.serve()

func handler():
    return "Hello from {name}!"
"#;

/// `src/main.buff` for the `ml` template (T0-C1).
///
/// Demonstrates the `buff-tensor` import surface. v1.15 runtime required
/// to actually dispatch tensor ops; the file is a starter.
pub const ML_MAIN_BUFF_TEMPLATE: &str = r#"// {name} - generated by `buff new --template ml`
// ML starter using buff-tensor (v1.15 runtime required to run).
// Tensors dispatch to GPU automatically when @prefer(gpu) is set.

import { Tensor } from "buff-tensor"

@prefer(gpu)
func train_step(xs: Tensor, ys: Tensor):
    let predictions = xs.multiply(ys)
    return predictions

func main():
    let xs = Tensor.zeros(Shape.of(64, 64))
    let ys = Tensor.ones(Shape.of(64, 64))
    let result = train_step(xs: xs, ys: ys)
    print(result)
"#;

/// `src/main.buff` for the `game` template (T0-C1).
///
/// Demonstrates the `buff-ecs` entity-component-system import surface.
/// v1.16 runtime required for the game loop.
pub const GAME_MAIN_BUFF_TEMPLATE: &str = r#"// {name} - generated by `buff new --template game`
// Game starter using buff-ecs (v1.16 runtime required to run).
// Define entities + systems; the engine drives the fixed-tick loop.

import { World, Entity, System } from "buff-ecs"

func main():
    let world = World.new()
    let player = world.spawn(Entity.new(name: "player"))
    world.add_system(System.new(update))
    world.run(fps: 60)

func update():
    print("tick")
"#;

/// `src/main.buff` for the `pipeline` template (T0-C1).
///
/// Demonstrates the `buff-dataframe` ETL import surface. v1.17 runtime
/// required for the pipeline runner.
pub const PIPELINE_MAIN_BUFF_TEMPLATE: &str = r#"// {name} - generated by `buff new --template pipeline`
// ETL pipeline starter using buff-dataframe (v1.17 runtime required to run).
// Stages compose left-to-right via the |> operator.

import { DataFrame, Pipeline } from "buff-dataframe"

func main():
    let df = DataFrame.load("input.csv")
    let result = df
        |> Pipeline.filter(row: row.value > 0)
        |> Pipeline.map(row: row.with_value(value: row.value * 2))
        |> Pipeline.collect()
    result.save("output.csv")
"#;

/// A single scaffolded file: a path relative to the project root and the
/// already-rendered content to write at that path.
pub type ScaffoldFile = (&'static str, String);

/// Returns the set of files to write for the given `template` + project `name`.
///
/// Paths are relative to the project root (e.g. `"src/main.buff"`). The
/// caller ([`crate::commands::new::run`]) is responsible for creating parent
/// directories and refusing to clobber an existing project directory.
///
/// Every template emits a root manifest (`buff.toml`), `.gitignore`, and
/// `README.md`; the template-specific files differ.
///
/// # T0-C1 — v2 template set
///
/// The 7 user-visible templates each emit a v2 manifest + a `tests/`
/// directory + an `examples/` directory + a CI workflow. Legacy
/// `Binary`/`Lib`/`Server`/`Gpu` paths preserve the v0.5/v1.0 layout
/// (v1 manifest, no tests/examples/CI) so existing integrations and
/// snapshot tests continue to work.
pub fn files_for_template(template: TemplateKind, name: &str) -> Vec<ScaffoldFile> {
    let render = |t: &str| render_template(t, name);
    let mut files: Vec<ScaffoldFile> = Vec::new();

    // Root manifest: Workspace gets a [workspace] table; everyone else the
    // standard [package] manifest.
    let root_toml = match template {
        TemplateKind::Workspace => WORKSPACE_BUFF_TOML_TEMPLATE,
        // Legacy Binary/Lib/Server/Gpu keep the v1 manifest for backward
        // compat (existing snapshot tests assert its shape). The 4 new
        // v2 templates opt into the v2 manifest.
        TemplateKind::Binary
        | TemplateKind::Lib
        | TemplateKind::Server
        | TemplateKind::Gpu => BUFF_TOML_TEMPLATE,
        TemplateKind::Web | TemplateKind::Ml | TemplateKind::Game | TemplateKind::Pipeline => {
            BUFF_TOML_V2_TEMPLATE
        }
    };
    files.push(("buff.toml", render(root_toml)));
    files.push((".gitignore", GITIGNORE_TEMPLATE.to_string()));
    files.push(("README.md", render(README_TEMPLATE)));

    // T0-I1: every template ships a CI workflow (3-OS matrix running
    // buff fmt + buff check + buff test). Universal so newly-scaffolded
    // projects work the same regardless of template.
    files.push((".github/workflows/ci.yml", CI_YML_TEMPLATE.to_string()));

    // T0-I2: the console template additionally ships a multi-stage
    // Dockerfile (builder + slim runtime). Other templates can ship
    // Dockerfiles in future tasks as their framework runtimes mature.
    if matches!(template, TemplateKind::Binary) {
        files.push(("Dockerfile", render(DOCKERFILE_TEMPLATE)));
    }

    // T0-C1: the 4 new templates also emit tests/ + examples/ +
    // .env.example (the latter signals the template is "v2-aware").
    let is_v2_template = matches!(
        template,
        TemplateKind::Web | TemplateKind::Ml | TemplateKind::Game | TemplateKind::Pipeline
    );
    if is_v2_template {
        files.push(("tests/test_hello.buff", render(TEST_HELLO_BUFF_TEMPLATE)));
        files.push(("examples/hello.buff", render(EXAMPLE_HELLO_BUFF_TEMPLATE)));
        files.push((".env.example", ENV_EXAMPLE_TEMPLATE.to_string()));
    }

    match template {
        TemplateKind::Binary => {
            files.push(("src/main.buff", render(MAIN_BUFF_TEMPLATE)));
        }
        TemplateKind::Lib => {
            files.push(("src/lib.buff", render(LIB_BUFF_TEMPLATE)));
        }
        TemplateKind::Server => {
            files.push(("src/main.buff", render(SERVER_MAIN_BUFF_TEMPLATE)));
        }
        TemplateKind::Gpu => {
            files.push(("src/main.buff", render(GPU_MAIN_BUFF_TEMPLATE)));
        }
        TemplateKind::Workspace => {
            files.push((
                "crates/core/buff.toml",
                render(WORKSPACE_MEMBER_BUFF_TOML_TEMPLATE),
            ));
            files.push((
                "crates/core/src/main.buff",
                render(WORKSPACE_CORE_MAIN_BUFF_TEMPLATE),
            ));
            files.push((
                "crates/utils/buff.toml",
                render(WORKSPACE_MEMBER_BUFF_TOML_TEMPLATE),
            ));
            files.push((
                "crates/utils/src/lib.buff",
                render(WORKSPACE_UTILS_LIB_BUFF_TEMPLATE),
            ));
        }
        TemplateKind::Web => {
            files.push(("src/main.buff", render(WEB_MAIN_BUFF_TEMPLATE)));
        }
        TemplateKind::Ml => {
            files.push(("src/main.buff", render(ML_MAIN_BUFF_TEMPLATE)));
        }
        TemplateKind::Game => {
            files.push(("src/main.buff", render(GAME_MAIN_BUFF_TEMPLATE)));
        }
        TemplateKind::Pipeline => {
            files.push(("src/main.buff", render(PIPELINE_MAIN_BUFF_TEMPLATE)));
        }
    }

    files
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn render_template_replaces_single_occurrence() {
        let rendered = render_template(BUFF_TOML_TEMPLATE, "my_app");
        assert!(rendered.contains("name = \"my_app\""));
        assert!(!rendered.contains("{name}"));
    }

    #[test]
    fn render_template_replaces_multiple_occurrences() {
        let rendered = render_template(README_TEMPLATE, "demo");
        // README references the name twice: header + (potentially) usage.
        assert!(rendered.matches("demo").count() >= 1);
        assert!(!rendered.contains("{name}"));
    }

    #[test]
    fn keywords_table_has_25_entries() {
        // Mirrors the lexer keyword count; if either side changes the other
        // must follow.
        assert_eq!(KEYWORDS.len(), 25, "Buff has 25 reserved keywords");
    }

    #[test]
    fn template_from_flags_defaults_to_binary() {
        assert_eq!(
            template_from_flags(false, false, false, false).unwrap(),
            TemplateKind::Binary
        );
    }

    #[test]
    fn template_from_flags_each_variant() {
        assert_eq!(
            template_from_flags(true, false, false, false).unwrap(),
            TemplateKind::Lib
        );
        assert_eq!(
            template_from_flags(false, true, false, false).unwrap(),
            TemplateKind::Server
        );
        assert_eq!(
            template_from_flags(false, false, true, false).unwrap(),
            TemplateKind::Gpu
        );
        assert_eq!(
            template_from_flags(false, false, false, true).unwrap(),
            TemplateKind::Workspace
        );
    }

    #[test]
    fn template_from_flags_rejects_multiple_set() {
        assert!(template_from_flags(true, true, false, false).is_err());
        assert!(template_from_flags(false, true, true, false).is_err());
        assert!(template_from_flags(true, false, false, true).is_err());
    }

    #[test]
    fn files_for_binary_matches_v01_layout() {
        let files = files_for_template(TemplateKind::Binary, "demo");
        let paths: Vec<_> = files.iter().map(|(p, _)| *p).collect();
        assert!(paths.contains(&"buff.toml"));
        assert!(paths.contains(&"src/main.buff"));
        assert!(paths.contains(&".gitignore"));
        assert!(paths.contains(&"README.md"));
        assert!(!paths.contains(&"src/lib.buff"));
    }

    #[test]
    fn files_for_lib_has_no_main() {
        let files = files_for_template(TemplateKind::Lib, "demo");
        let paths: Vec<_> = files.iter().map(|(p, _)| *p).collect();
        assert!(paths.contains(&"src/lib.buff"));
        assert!(!paths.contains(&"src/main.buff"));
    }

    #[test]
    fn files_for_workspace_has_member_layout() {
        let files = files_for_template(TemplateKind::Workspace, "demo");
        let paths: Vec<_> = files.iter().map(|(p, _)| *p).collect();
        assert!(paths.contains(&"crates/core/buff.toml"));
        assert!(paths.contains(&"crates/core/src/main.buff"));
        assert!(paths.contains(&"crates/utils/buff.toml"));
        assert!(paths.contains(&"crates/utils/src/lib.buff"));
    }

    // -----------------------------------------------------------------------
    // T0-C1 — v2 template set
    // -----------------------------------------------------------------------

    #[test]
    fn template_from_name_recognises_all_user_visible() {
        for kind in TemplateKind::user_visible() {
            let name = kind.as_kebab();
            let resolved = template_from_name(name).expect("user-visible name resolves");
            assert_eq!(resolved, *kind, "mismatch for name `{name}`");
        }
    }

    #[test]
    fn template_from_name_accepts_legacy_binary_alias() {
        // "binary" is the v0.5 kebab name; it maps to the same variant as "console".
        let resolved = template_from_name("binary").expect("legacy alias works");
        assert_eq!(resolved, TemplateKind::Binary);
    }

    #[test]
    fn template_from_name_rejects_unknown() {
        let err = template_from_name("nonexistent").expect_err("unknown name must error");
        assert!(err.contains("console"), "err lists valid names: {err}");
        assert!(err.contains("workspace"), "err lists valid names: {err}");
    }

    #[test]
    fn binary_kebab_is_console_in_v2() {
        // T0-C1: the user-visible name for the default template is "console".
        assert_eq!(TemplateKind::Binary.as_kebab(), "console");
    }

    #[test]
    fn user_visible_lists_exactly_seven_templates() {
        assert_eq!(TemplateKind::user_visible().len(), 7, "exactly 7 v2 templates");
    }

    #[test]
    fn v2_templates_emit_full_layout() {
        for kind in [
            TemplateKind::Web,
            TemplateKind::Ml,
            TemplateKind::Game,
            TemplateKind::Pipeline,
        ] {
            let files = files_for_template(kind, "demo");
            let paths: Vec<&str> = files.iter().map(|(p, _)| *p).collect();
            assert!(paths.contains(&"buff.toml"), "{:?} missing buff.toml", kind);
            assert!(paths.contains(&"src/main.buff"), "{:?} missing src/main.buff", kind);
            assert!(
                paths.contains(&"tests/test_hello.buff"),
                "{:?} missing tests/test_hello.buff",
                kind
            );
            assert!(
                paths.contains(&"examples/hello.buff"),
                "{:?} missing examples/hello.buff",
                kind
            );
            assert!(paths.contains(&"README.md"), "{:?} missing README.md", kind);
            assert!(
                paths.contains(&".github/workflows/ci.yml"),
                "{:?} missing CI workflow",
                kind
            );
            assert!(paths.contains(&".gitignore"), "{:?} missing .gitignore", kind);
            assert!(paths.contains(&".env.example"), "{:?} missing .env.example", kind);
        }
    }

    #[test]
    fn v2_manifest_emits_stability_and_edition_2026() {
        let files = files_for_template(TemplateKind::Web, "demo");
        let buff_toml = files
            .iter()
            .find(|(p, _)| *p == "buff.toml")
            .map(|(_, c)| c.as_str())
            .expect("buff.toml present");
        assert!(
            buff_toml.contains("edition = \"2026\""),
            "v2 edition missing: {buff_toml}"
        );
        assert!(
            buff_toml.contains("stability = \"experimental\""),
            "stability missing: {buff_toml}"
        );
        assert!(
            buff_toml.contains("[features]"),
            "[features] section missing: {buff_toml}"
        );
        assert!(
            buff_toml.contains("[lints]"),
            "[lints] section missing: {buff_toml}"
        );
    }

    #[test]
    fn v2_template_main_buff_uses_framework_imports() {
        let web = files_for_template(TemplateKind::Web, "demo");
        let main = web
            .iter()
            .find(|(p, _)| *p == "src/main.buff")
            .map(|(_, c)| c.as_str())
            .expect("web main.buff");
        assert!(main.contains("buff-web"), "web template imports buff-web: {main}");

        let ml = files_for_template(TemplateKind::Ml, "demo");
        let main = ml
            .iter()
            .find(|(p, _)| *p == "src/main.buff")
            .map(|(_, c)| c.as_str())
            .expect("ml main.buff");
        assert!(main.contains("buff-tensor"), "ml template imports buff-tensor: {main}");

        let game = files_for_template(TemplateKind::Game, "demo");
        let main = game
            .iter()
            .find(|(p, _)| *p == "src/main.buff")
            .map(|(_, c)| c.as_str())
            .expect("game main.buff");
        assert!(main.contains("buff-ecs"), "game template imports buff-ecs: {main}");

        let pipe = files_for_template(TemplateKind::Pipeline, "demo");
        let main = pipe
            .iter()
            .find(|(p, _)| *p == "src/main.buff")
            .map(|(_, c)| c.as_str())
            .expect("pipeline main.buff");
        assert!(
            main.contains("buff-dataframe"),
            "pipeline template imports buff-dataframe: {main}"
        );
    }

    #[test]
    fn ci_yml_template_runs_three_os_matrix() {
        let files = files_for_template(TemplateKind::Web, "demo");
        let ci = files
            .iter()
            .find(|(p, _)| *p == ".github/workflows/ci.yml")
            .map(|(_, c)| c.as_str())
            .expect("ci.yml present");
        assert!(ci.contains("ubuntu-latest"), "ci: {ci}");
        assert!(ci.contains("windows-latest"), "ci: {ci}");
        assert!(ci.contains("macos-latest"), "ci: {ci}");
        assert!(ci.contains("buff fmt --check"), "ci runs buff fmt: {ci}");
        assert!(ci.contains("buff check -D"), "ci runs buff check: {ci}");
        assert!(ci.contains("buff test"), "ci runs buff test: {ci}");
    }

    // -----------------------------------------------------------------------
    // T0-I1 + T0-I2 — universal CI + console Dockerfile
    // -----------------------------------------------------------------------

    #[test]
    fn every_template_ships_ci_workflow() {
        // T0-I1: .github/workflows/ci.yml is universal across ALL templates,
        // including the legacy Binary/Lib/Server/Gpu/Workspace paths.
        for kind in [
            TemplateKind::Binary,
            TemplateKind::Lib,
            TemplateKind::Server,
            TemplateKind::Gpu,
            TemplateKind::Workspace,
            TemplateKind::Web,
            TemplateKind::Ml,
            TemplateKind::Game,
            TemplateKind::Pipeline,
        ] {
            let files = files_for_template(kind, "demo");
            let paths: Vec<&str> = files.iter().map(|(p, _)| *p).collect();
            assert!(
                paths.contains(&".github/workflows/ci.yml"),
                "{:?} missing CI workflow",
                kind
            );
        }
    }

    #[test]
    fn console_template_ships_dockerfile() {
        // T0-I2: only the console (Binary) template ships a Dockerfile.
        let files = files_for_template(TemplateKind::Binary, "demo");
        let paths: Vec<&str> = files.iter().map(|(p, _)| *p).collect();
        assert!(paths.contains(&"Dockerfile"), "console missing Dockerfile");
    }

    #[test]
    fn non_console_templates_skip_dockerfile() {
        for kind in [
            TemplateKind::Lib,
            TemplateKind::Server,
            TemplateKind::Gpu,
            TemplateKind::Workspace,
            TemplateKind::Web,
            TemplateKind::Ml,
            TemplateKind::Game,
            TemplateKind::Pipeline,
        ] {
            let files = files_for_template(kind, "demo");
            let paths: Vec<&str> = files.iter().map(|(p, _)| *p).collect();
            assert!(
                !paths.contains(&"Dockerfile"),
                "{:?} should NOT ship a Dockerfile (console-only for v1.13)",
                kind
            );
        }
    }

    #[test]
    fn dockerfile_template_uses_multistage_build() {
        let files = files_for_template(TemplateKind::Binary, "demo");
        let dockerfile = files
            .iter()
            .find(|(p, _)| *p == "Dockerfile")
            .map(|(_, c)| c.as_str())
            .expect("Dockerfile present");
        assert!(
            dockerfile.contains("FROM ghcr.io/buff-lang/buff:builder AS build"),
            "missing builder stage: {dockerfile}"
        );
        assert!(
            dockerfile.contains("FROM ghcr.io/buff-lang/buff:slim"),
            "missing slim runtime stage: {dockerfile}"
        );
        assert!(
            dockerfile.contains("buff build --release"),
            "missing build step: {dockerfile}"
        );
    }
}
