//! Project scaffolding — templates and validation shared by `buff new` and
//! `buff init`.
//!
//! Templates are plain strings with a single `{name}` placeholder substituted
//! by [`render_template`]. They are deliberately simple (no TPL engine dep):
//! the v0.1 generated project is four small files, and a `str::replace` call
//! keeps the dependency surface minimal.
//!
//! [`validate_project_name`] enforces the same identifier rules the lexer will
//! later apply to symbols, plus a check against the 25 reserved keywords (see
//! `crates/buff-lang-lexer/src/token.rs`).

/// Reserved Buff keywords (must match the lexer's keyword table).
///
/// Sourcing this as a static array here (instead of importing from the lexer)
/// keeps `buff new` / `buff init` decoupled from lexer internals — the keyword
/// list is small and stable for v0.1.
pub const KEYWORDS: &[&str] = &[
    "func", "let", "mut", "struct", "enum", "trait", "type", "if", "else", "for", "return",
    "break", "continue", "in", "match", "async", "spawn", "import", "export", "from", "as", "true",
    "false", "extern", "unsafe",
];

/// `buff.toml` manifest template.
///
/// `{name}` is replaced with the project name. The `edition` field tracks the
/// Buff language edition (semver-ish); v0.1 emits `"0.1"`.
pub const BUFF_TOML_TEMPLATE: &str = r#"[package]
name = "{name}"
version = "0.1.0"
edition = "0.1"
"#;

/// `src/main.buff` entry-point template.
///
/// `{name}` is referenced in a leading comment. The body is the canonical v0.1
/// "Hello, Buff!" program and is runnable via `buff run src/main.buff`.
pub const MAIN_BUFF_TEMPLATE: &str = r#"// {name} - generated by `buff new`
func main():
    print("Hello, Buff!")
"#;

/// `.gitignore` template emitted into the project root.
///
/// Ignores the cargo `target/` tree, the per-project `buff.lock`, and any
/// stray generated `.rs` files (the transpiler writes them next to the source
/// — keeping them out of VCS is the user's signal that they're build artifacts).
pub const GITIGNORE_TEMPLATE: &str = r#"target/
buff.lock
*.rs
"#;

/// `README.md` template — minimal usage instructions referencing `buff run`.
pub const README_TEMPLATE: &str = r#"# {name}

Generated by `buff new`.

## Run

```
buff run src/main.buff
```
"#;

/// Validate a project name.
///
/// Rules:
/// - Non-empty.
/// - Starts with an ASCII letter or underscore (not a digit, not unicode).
/// - Subsequent characters are ASCII alphanumeric or underscore.
/// - Not a reserved Buff keyword (see [`KEYWORDS`]).
///
/// # Errors
///
/// Returns a human-readable `String` describing the first violated rule. The
/// message is suitable for direct display to the user via `anyhow::Error::msg`.
pub fn validate_project_name(name: &str) -> Result<(), String> {
    if name.is_empty() {
        return Err("project name cannot be empty".to_string());
    }
    let first = name.chars().next().expect("checked non-empty above");
    if !first.is_ascii_alphabetic() && first != '_' {
        return Err(format!(
            "project name must start with a letter or underscore: `{name}`"
        ));
    }
    if !name.chars().all(|c| c.is_ascii_alphanumeric() || c == '_') {
        return Err(format!(
            "project name contains invalid characters (allowed: a-z, A-Z, 0-9, _): `{name}`"
        ));
    }
    if KEYWORDS.contains(&name) {
        return Err(format!(
            "invalid project name: `{name}` is a reserved Buff keyword"
        ));
    }
    Ok(())
}

/// Substitute the `{name}` placeholder in a template string.
///
/// Uses plain `str::replace`, which replaces *all* occurrences (templates may
/// reference the name multiple times, e.g. the README header and run command).
pub fn render_template(template: &str, name: &str) -> String {
    template.replace("{name}", name)
}

// ===========================================================================
// Template kinds (T112) — `buff new --{lib,server,gpu,workspace}`
// ===========================================================================

/// The kind of project to scaffold via `buff new` / `buff init` (T112).
///
/// Each variant selects a different starter layout (see [`files_for_template`]).
/// [`TemplateKind::Binary`] is the default and matches the original v0.1
/// `buff new` behavior (a runnable `src/main.buff`).
///
/// The `Server` and `Gpu` templates produce *starter* Buff source files that
/// demonstrate the intended async / GPU-dispatch syntax. Running them
/// end-to-end depends on the v1.0 runtime (`tokio` + `wgpu`), so in v0.5 the
/// file is created with reasonable starter content but `buff run` on it is
/// not yet expected to link.
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq)]
pub enum TemplateKind {
    /// A runnable application with `src/main.buff` (default; v0.1 behavior).
    #[default]
    Binary,
    /// A library module with `src/lib.buff` exporting functions for import.
    Lib,
    /// An async server starter (`async func` + `spawn`); v1.0 runtime to run.
    Server,
    /// A GPU-dispatch starter carrying `@prefer(gpu)` hints; v1.0 runtime to run.
    Gpu,
    /// A multi-crate workspace layout with member directories under `crates/`.
    Workspace,
}

impl TemplateKind {
    /// Lowercase kebab-name used in user-facing messages and (potentially)
    /// `--template <name>` options. Kept here so the CLI and any future
    /// `--template` value parser share a single source of truth.
    pub fn as_kebab(&self) -> &'static str {
        match self {
            TemplateKind::Binary => "binary",
            TemplateKind::Lib => "lib",
            TemplateKind::Server => "server",
            TemplateKind::Gpu => "gpu",
            TemplateKind::Workspace => "workspace",
        }
    }
}

/// Selects a [`TemplateKind`] from individual CLI boolean flags (T112).
///
/// Maps the `--lib` / `--server` / `--gpu` / `--workspace` flags from the
/// `New` clap variant onto a single [`TemplateKind`]. At most one flag may be
/// `true`; if all are `false`, returns [`TemplateKind::Binary`] (the default
/// — preserves the v0.1 `buff new NAME` behavior with no regressions).
///
/// # Errors
///
/// Returns a human-readable `String` if more than one flag is set.
pub fn template_from_flags(
    lib: bool,
    server: bool,
    gpu: bool,
    workspace: bool,
) -> Result<TemplateKind, String> {
    let set = [lib, server, gpu, workspace].iter().filter(|&&b| b).count();
    if set > 1 {
        return Err(
            "at most one template flag may be set (--lib, --server, --gpu, --workspace)"
                .to_string(),
        );
    }
    Ok(match (lib, server, gpu, workspace) {
        (true, _, _, _) => TemplateKind::Lib,
        (_, true, _, _) => TemplateKind::Server,
        (_, _, true, _) => TemplateKind::Gpu,
        (_, _, _, true) => TemplateKind::Workspace,
        _ => TemplateKind::Binary,
    })
}

// ---------------------------------------------------------------------------
// Per-template content strings
// ---------------------------------------------------------------------------

/// `src/lib.buff` library template (T112 `--lib`).
///
/// Exports two starter functions (`greet`, `add`) with no `func main()` — a
/// library is consumed via `import { greet } from "./name"`, not run directly.
pub const LIB_BUFF_TEMPLATE: &str = r#"// {name} - generated by `buff new --lib`
// Library module. Exported functions are importable by other Buff programs:
//     import { greet } from "./{name}"

export func greet(name):
    print("Hello, " + name + "!")

export func add(a, b):
    return a + b
"#;

/// `src/main.buff` async server template (T112 `--server`).
///
/// Demonstrates the Buff async-without-`await` model: `async func` seeds the
/// call-graph propagation, `spawn` schedules a task, and `.result()` joins.
/// Running requires the Buff `tokio` runtime (v1.0); the file is a starter
/// in v0.5.
pub const SERVER_MAIN_BUFF_TEMPLATE: &str = r#"// {name} - generated by `buff new --server`
// Async server template. Running requires the Buff tokio runtime (v1.0).
// There is NO `await` keyword in Buff — async propagates up the call graph
// automatically, and `.result()` joins a spawned task.

async func handler():
    return "Hello from {name}!"

func main():
    let task = spawn handler()
    let message = task.result()
    print(message)
"#;

/// `src/main.buff` GPU-dispatch template (T112 `--gpu`).
///
/// Carries an `@prefer(gpu)` hint on a compute-style function. Real GPU
/// dispatch (WGSL shader emission + `wgpu` host) arrives in v1.0; the
/// function falls back to CPU automatically when no GPU is present.
pub const GPU_MAIN_BUFF_TEMPLATE: &str = r#"// {name} - generated by `buff new --gpu`
// GPU dispatch template. `@prefer(gpu)` hints the compiler to dispatch the
// annotated function on the GPU when hardware is available (v1.0 runtime).
// When no GPU is present the function runs on CPU — the hint never breaks.

@prefer(gpu)
func compute(a, b):
    return a * b

func main():
    let result = compute(21, 2)
    print(result)
"#;

/// Workspace-root `buff.toml` template (T112 `--workspace`).
///
/// Mirrors Cargo's `[workspace]` manifest shape: a workspace-level manifest
/// lists member crates under `crates/`. The Buff workspace resolver itself
/// is a v1.0 concern; the scaffold produces a structurally-correct starter.
pub const WORKSPACE_BUFF_TOML_TEMPLATE: &str = r#"[workspace]
name = "{name}"
version = "0.1.0"
edition = "0.1"
members = ["crates/core", "crates/utils"]
"#;

/// Workspace member `core/src/main.buff` template — binary crate entry point.
pub const WORKSPACE_CORE_MAIN_BUFF_TEMPLATE: &str = r#"// {name} workspace - core crate entry point
func main():
    print("Hello from {name} core!")
"#;

/// Workspace member `utils/src/lib.buff` template — library crate.
pub const WORKSPACE_UTILS_LIB_BUFF_TEMPLATE: &str = r#"// {name} workspace - utils crate library
export func helper():
    print("utils helper called")
"#;

/// Workspace member `buff.toml` template (shared by `core` and `utils`).
pub const WORKSPACE_MEMBER_BUFF_TOML_TEMPLATE: &str = r#"[package]
name = "{name}"
version = "0.1.0"
edition = "0.1"
"#;

/// A single scaffolded file: a path relative to the project root and the
/// already-rendered content to write at that path.
pub type ScaffoldFile = (&'static str, String);

/// Returns the set of files to write for the given `template` + project `name`.
///
/// Paths are relative to the project root (e.g. `"src/main.buff"`). The
/// caller ([`crate::commands::new::run`]) is responsible for creating parent
/// directories and refusing to clobber an existing project directory.
///
/// Every template emits a root manifest (`buff.toml`), `.gitignore`, and
/// `README.md`; the template-specific files differ.
pub fn files_for_template(template: TemplateKind, name: &str) -> Vec<ScaffoldFile> {
    let render = |t: &str| render_template(t, name);
    let mut files: Vec<ScaffoldFile> = Vec::new();

    // Root manifest: Workspace gets a [workspace] table; everyone else the
    // standard [package] manifest.
    let root_toml = match template {
        TemplateKind::Workspace => WORKSPACE_BUFF_TOML_TEMPLATE,
        _ => BUFF_TOML_TEMPLATE,
    };
    files.push(("buff.toml", render(root_toml)));
    files.push((".gitignore", GITIGNORE_TEMPLATE.to_string()));
    files.push(("README.md", render(README_TEMPLATE)));

    match template {
        TemplateKind::Binary => {
            files.push(("src/main.buff", render(MAIN_BUFF_TEMPLATE)));
        }
        TemplateKind::Lib => {
            files.push(("src/lib.buff", render(LIB_BUFF_TEMPLATE)));
        }
        TemplateKind::Server => {
            files.push(("src/main.buff", render(SERVER_MAIN_BUFF_TEMPLATE)));
        }
        TemplateKind::Gpu => {
            files.push(("src/main.buff", render(GPU_MAIN_BUFF_TEMPLATE)));
        }
        TemplateKind::Workspace => {
            files.push((
                "crates/core/buff.toml",
                render(WORKSPACE_MEMBER_BUFF_TOML_TEMPLATE),
            ));
            files.push((
                "crates/core/src/main.buff",
                render(WORKSPACE_CORE_MAIN_BUFF_TEMPLATE),
            ));
            files.push((
                "crates/utils/buff.toml",
                render(WORKSPACE_MEMBER_BUFF_TOML_TEMPLATE),
            ));
            files.push((
                "crates/utils/src/lib.buff",
                render(WORKSPACE_UTILS_LIB_BUFF_TEMPLATE),
            ));
        }
    }

    files
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn render_template_replaces_single_occurrence() {
        let rendered = render_template(BUFF_TOML_TEMPLATE, "my_app");
        assert!(rendered.contains("name = \"my_app\""));
        assert!(!rendered.contains("{name}"));
    }

    #[test]
    fn render_template_replaces_multiple_occurrences() {
        let rendered = render_template(README_TEMPLATE, "demo");
        // README references the name twice: header + (potentially) usage.
        assert!(rendered.matches("demo").count() >= 1);
        assert!(!rendered.contains("{name}"));
    }

    #[test]
    fn keywords_table_has_25_entries() {
        // Mirrors the lexer keyword count; if either side changes the other
        // must follow.
        assert_eq!(KEYWORDS.len(), 25, "Buff has 25 reserved keywords");
    }

    #[test]
    fn template_from_flags_defaults_to_binary() {
        assert_eq!(
            template_from_flags(false, false, false, false).unwrap(),
            TemplateKind::Binary
        );
    }

    #[test]
    fn template_from_flags_each_variant() {
        assert_eq!(
            template_from_flags(true, false, false, false).unwrap(),
            TemplateKind::Lib
        );
        assert_eq!(
            template_from_flags(false, true, false, false).unwrap(),
            TemplateKind::Server
        );
        assert_eq!(
            template_from_flags(false, false, true, false).unwrap(),
            TemplateKind::Gpu
        );
        assert_eq!(
            template_from_flags(false, false, false, true).unwrap(),
            TemplateKind::Workspace
        );
    }

    #[test]
    fn template_from_flags_rejects_multiple_set() {
        assert!(template_from_flags(true, true, false, false).is_err());
        assert!(template_from_flags(false, true, true, false).is_err());
        assert!(template_from_flags(true, false, false, true).is_err());
    }

    #[test]
    fn files_for_binary_matches_v01_layout() {
        let files = files_for_template(TemplateKind::Binary, "demo");
        let paths: Vec<_> = files.iter().map(|(p, _)| *p).collect();
        assert!(paths.contains(&"buff.toml"));
        assert!(paths.contains(&"src/main.buff"));
        assert!(paths.contains(&".gitignore"));
        assert!(paths.contains(&"README.md"));
        assert!(!paths.contains(&"src/lib.buff"));
    }

    #[test]
    fn files_for_lib_has_no_main() {
        let files = files_for_template(TemplateKind::Lib, "demo");
        let paths: Vec<_> = files.iter().map(|(p, _)| *p).collect();
        assert!(paths.contains(&"src/lib.buff"));
        assert!(!paths.contains(&"src/main.buff"));
    }

    #[test]
    fn files_for_workspace_has_member_layout() {
        let files = files_for_template(TemplateKind::Workspace, "demo");
        let paths: Vec<_> = files.iter().map(|(p, _)| *p).collect();
        assert!(paths.contains(&"crates/core/buff.toml"));
        assert!(paths.contains(&"crates/core/src/main.buff"));
        assert!(paths.contains(&"crates/utils/buff.toml"));
        assert!(paths.contains(&"crates/utils/src/lib.buff"));
    }
}
