//! `buff doc` — placeholder per-crate HTML API docs (T0-E3 scaffold).
//!
//! v1.13 ships only the command scaffold so users can wire it into CI
//! today. The command:
//!
//! 1. Reads `buff.toml` from the current directory for `[package].name`.
//! 2. Walks `src/` for `.buff` files (recursive).
//! 3. Emits `docs/<package>/index.html` per crate with a placeholder
//!    page listing every `.buff` file + every top-level `export` decl
//!    (parsed; not yet type-resolved).
//! 4. Emits a top-level `docs/index.html` with links to each crate's
//!    page (workspace mode — single-crate projects get just one page).
//!
//! **Full rendering is deferred to v1.18+.** The scaffold produces
//! minimal but valid HTML so links resolve and the file structure is
//! stable. Rustdoc-quality rendering (cross-refs, type signatures,
//! search) is out of scope.

use std::collections::BTreeMap;
use std::fs;
use std::path::{Path, PathBuf};

use anyhow::{Context, Result};
use buff_lang_lexer::tokenize;
use buff_lang_parser::parse;

use crate::config::BuffConfig;

/// Entry point for `buff doc`.
///
/// Reads `buff.toml` from `dir`, walks `src/` for `.buff` files, emits
/// HTML to `docs/`. Idempotent: re-running overwrites the previous
/// output (matches `cargo doc` behaviour).
pub fn run(dir: &Path) -> Result<()> {
    let manifest_path = dir.join("buff.toml");
    let cfg = BuffConfig::load_from_file(&manifest_path)
        .with_context(|| format!("failed to read manifest at {}", manifest_path.display()))?;

    let docs_root = dir.join("docs");
    fs::create_dir_all(&docs_root)
        .with_context(|| format!("failed to create {}", docs_root.display()))?;

    // Single-package vs workspace mode.
    let packages: Vec<(String, PathBuf)> = if let Some(p) = &cfg.package {
        vec![(p.name.clone(), dir.to_path_buf())]
    } else if let Some(ws) = &cfg.workspace {
        ws.members
            .iter()
            .filter_map(|m| {
                let member_dir = dir.join(m);
                let member_manifest = member_dir.join("buff.toml");
                BuffConfig::load_from_file(&member_manifest)
                    .ok()
                    .and_then(|c| c.package.map(|p| (p.name, member_dir)))
            })
            .collect()
    } else {
        return Err(anyhow::anyhow!(
            "buff.toml has neither [package] nor [workspace] — nothing to document"
        ));
    };

    let mut crate_indexes: Vec<(String, String)> = Vec::new();
    for (pkg_name, pkg_dir) in &packages {
        let crate_docs_dir = docs_root.join(pkg_name);
        fs::create_dir_all(&crate_docs_dir).with_context(|| {
            format!("failed to create {}", crate_docs_dir.display())
        })?;
        let html = render_crate_page(pkg_name, pkg_dir);
        let out = crate_docs_dir.join("index.html");
        fs::write(&out, &html)
            .with_context(|| format!("failed to write {}", out.display()))?;
        crate_indexes.push((pkg_name.clone(), format!("{pkg_name}/index.html")));
    }

    // Top-level index linking to each crate page.
    let index_html = render_workspace_index(&crate_indexes);
    let index_path = docs_root.join("index.html");
    fs::write(&index_path, &index_html)
        .with_context(|| format!("failed to write {}", index_path.display()))?;

    eprintln!(
        "Generated placeholder docs for {} crate(s) under {}/",
        packages.len(),
        docs_root.display()
    );
    eprintln!("Open {}/index.html to browse.", docs_root.display());
    Ok(())
}

/// Render a single crate's placeholder page. Walks `src/` for `.buff`
/// files and lists every top-level `export` decl found via the parser.
fn render_crate_page(pkg_name: &str, pkg_dir: &Path) -> String {
    let mut sections: BTreeMap<String, Vec<String>> = BTreeMap::new();
    let src_dir = pkg_dir.join("src");
    if src_dir.is_dir() {
        walk_buff_files(&src_dir, &src_dir, &mut sections);
    }

    let mut html = format!(
        "<!DOCTYPE html>\n<html>\n<head>\n  <meta charset=\"utf-8\">\n  \
         <title>{pkg_name} — Buff docs</title>\n</head>\n<body>\n\
         <h1>{pkg_name}</h1>\n\
         <p><em>Placeholder page generated by <code>buff doc</code>. \
         Full rendering arrives in v1.18+.</em></p>\n"
    );
    if sections.is_empty() {
        html.push_str("<p>No .buff source files found under <code>src/</code>.</p>\n");
    } else {
        for (file, exports) in &sections {
            html.push_str(&format!(
                "<h2><code>{file}</code></h2>\n<ul>\n"
            ));
            if exports.is_empty() {
                html.push_str("  <li><em>(no top-level exports)</em></li>\n");
            } else {
                for exp in exports {
                    html.push_str(&format!("  <li>{exp}</li>\n"));
                }
            }
            html.push_str("</ul>\n");
        }
    }
    html.push_str("</body>\n</html>\n");
    html
}

/// Recursive walker: discover every `.buff` file under `root`, parse
/// it, collect its top-level `export` decl names into `sections`.
fn walk_buff_files(
    current: &Path,
    root: &Path,
    sections: &mut BTreeMap<String, Vec<String>>,
) {
    let Ok(entries) = fs::read_dir(current) else {
        return;
    };
    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() {
            walk_buff_files(&path, root, sections);
        } else if path.extension().is_some_and(|e| e == "buff") {
            let rel = path
                .strip_prefix(root)
                .map(|p| p.display().to_string())
                .unwrap_or_else(|_| path.display().to_string());
            let exports = collect_exports(&path);
            sections.insert(rel, exports);
        }
    }
}

/// Parse `path` and collect the names of every top-level `export` decl.
/// Failures (lex/parse errors) yield an empty Vec — `buff doc` is
/// best-effort and does NOT surface compile errors (that's `buff check`'s
/// job). The user sees the file listed but with no exports.
fn collect_exports(path: &Path) -> Vec<String> {
    let Ok(src) = fs::read_to_string(path) else {
        return Vec::new();
    };
    let Ok(tokens) = tokenize(&src, buff_lang_error::SourceId(0)) else {
        return Vec::new();
    };
    let Ok(decls) = parse(&tokens, buff_lang_error::SourceId(0)) else {
        return Vec::new();
    };
    let mut exports = Vec::new();
    for decl in decls {
        if let buff_lang_ast::Decl::ExportDecl(e) = decl {
            exports.push(format!("{}", e.inner));
        }
    }
    exports
}

/// Render the top-level workspace index linking to each crate page.
fn render_workspace_index(crate_indexes: &[(String, String)]) -> String {
    let mut html = String::from(
        "<!DOCTYPE html>\n<html>\n<head>\n  <meta charset=\"utf-8\">\n  \
         <title>Buff docs — workspace index</title>\n</head>\n<body>\n\
         <h1>Buff docs</h1>\n<ul>\n",
    );
    if crate_indexes.is_empty() {
        html.push_str("  <li><em>No crates documented.</em></li>\n");
    } else {
        for (name, href) in crate_indexes {
            html.push_str(&format!(
                "  <li><a href=\"{href}\">{name}</a></li>\n"
            ));
        }
    }
    html.push_str("</ul>\n</body>\n</html>\n");
    html
}
