//! `buff gen <kind> <name>` — code generators that reduce boilerplate (T0-C2).
//!
//! Three generators, each producing a stub file the user fills in:
//!
//! - `buff gen module <name>` — creates `src/modules/<name>.buff` +
//!   `tests/unit/test_<name>.buff`. The module file exports an empty
//!   function; the test file imports it and has a single `@test` stub.
//! - `buff gen test <name>` — creates `tests/unit/<name>.buff` with a
//!   single `@test` stub fn.
//! - `buff gen example <name>` — creates `examples/<name>.buff` with a
//!   `func main():` stub.
//!
//! All three refuse to clobber existing files (the user must delete the
//! file first — defensive against accidental data loss).
//!
//! # Project layout assumption
//!
//! `buff gen` assumes the v2 project layout (see
//! `.sisyphus/decisions/sdk-conventions-v1x.md` §1.1): `src/modules/`,
//! `tests/unit/`, `examples/`. Running it outside a v2 project still
//! works (parent directories are created on demand), but the user is
//! encouraged to upgrade via `buff new --template console`.

use std::fs;
use std::path::PathBuf;

use anyhow::{bail, Context, Result};

use crate::scaffold::validate_project_name;

/// The kind of artifact `buff gen` produces.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum GenKind {
    Module,
    Test,
    Example,
}

impl GenKind {
    /// Lowercase kebab name used in user-facing messages.
    pub fn as_kebab(&self) -> &'static str {
        match self {
            GenKind::Module => "module",
            GenKind::Test => "test",
            GenKind::Example => "example",
        }
    }
}

/// Parse the kind from the CLI subcommand string. Returns `None` on
/// unknown kind so the caller can surface a "valid kinds are ..." error.
pub fn kind_from_str(s: &str) -> Option<GenKind> {
    match s {
        "module" => Some(GenKind::Module),
        "test" => Some(GenKind::Test),
        "example" => Some(GenKind::Example),
        _ => None,
    }
}

/// Entry point for `buff gen <kind> <name>`.
///
/// Validates `name`, computes the file(s) to write, refuses to clobber
/// existing files, then writes the stub content. Parent directories are
/// created on demand (matches `buff new` behaviour).
pub fn run(kind: GenKind, name: &str) -> Result<()> {
    validate_artifact_name(name)?;

    let files = files_for_gen(kind, name);
    // Refuse to clobber ANY of the files — partial clobber would leave
    // the project in an inconsistent state.
    for (path, _) in &files {
        if PathBuf::from(path).exists() {
            bail!(
                "refusing to overwrite existing file: {path} \
                 (delete it first if you want to regenerate)"
            );
        }
    }
    for (rel_path, content) in files {
        let full = PathBuf::from(&rel_path);
        if let Some(parent) = full.parent() {
            fs::create_dir_all(parent)
                .with_context(|| format!("failed to create directory `{}`", parent.display()))?;
        }
        fs::write(&full, content)
            .with_context(|| format!("failed to write `{}`", full.display()))?;
    }
    match kind {
        GenKind::Module => {
            eprintln!("Created module `src/modules/{name}.buff` + test stub.");
        }
        GenKind::Test => {
            eprintln!("Created test `tests/unit/{name}.buff`.");
        }
        GenKind::Example => {
            eprintln!("Created example `examples/{name}.buff`.");
        }
    }
    Ok(())
}

/// Validate the artifact name. Same rules as project names (Buff
/// identifier, not a keyword). Re-uses [`validate_project_name`] since
/// module/test/example names follow the same identifier rules.
fn validate_artifact_name(name: &str) -> Result<(), String> {
    validate_project_name(name)
}

/// Compute the (path, content) pairs to write for the given kind + name.
///
/// Returned as `Vec<(String, String)>` so the caller can iterate without
/// borrowing. Paths are relative to the project root (cwd of `buff gen`).
fn files_for_gen(kind: GenKind, name: &str) -> Vec<(String, String)> {
    match kind {
        GenKind::Module => {
            let module_path = format!("src/modules/{name}.buff");
            let test_path = format!("tests/unit/test_{name}.buff");
            vec![
                (module_path, render_module_stub(name)),
                (test_path, render_module_test_stub(name)),
            ]
        }
        GenKind::Test => {
            vec![(format!("tests/unit/{name}.buff"), render_test_stub(name))]
        }
        GenKind::Example => vec![(
            format!("examples/{name}.buff"),
            render_example_stub(name),
        )],
    }
}

fn render_module_stub(name: &str) -> String {
    format!(
        r#"// {name} module — generated by `buff gen module {name}`.

export func placeholder():
    return 0
"#
    )
}

fn render_module_test_stub(name: &str) -> String {
    format!(
        r#"// Tests for the {name} module — generated by `buff gen module {name}`.

import {{ placeholder }} from "../../src/modules/{name}"

@test
fn test_placeholder():
    let result = placeholder()
    assert(result == 0)
"#
    )
}

fn render_test_stub(name: &str) -> String {
    format!(
        r#"// {name} tests — generated by `buff gen test {name}`.

@test
fn test_{name}():
    assert(true)
"#
    )
}

fn render_example_stub(name: &str) -> String {
    format!(
        r#"// {name} example — generated by `buff gen example {name}`.
// Run with: buff run examples/{name}.buff

func main():
    print("Hello from the {name} example!")
"#
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn kind_from_str_recognises_three_variants() {
        assert_eq!(kind_from_str("module"), Some(GenKind::Module));
        assert_eq!(kind_from_str("test"), Some(GenKind::Test));
        assert_eq!(kind_from_str("example"), Some(GenKind::Example));
        assert_eq!(kind_from_str("nonsense"), None);
    }

    #[test]
    fn module_gen_produces_two_files() {
        let files = files_for_gen(GenKind::Module, "user");
        assert_eq!(files.len(), 2);
        assert_eq!(files[0].0, "src/modules/user.buff");
        assert_eq!(files[1].0, "tests/unit/test_user.buff");
    }

    #[test]
    fn test_gen_produces_one_file() {
        let files = files_for_gen(GenKind::Test, "smoke");
        assert_eq!(files.len(), 1);
        assert_eq!(files[0].0, "tests/unit/smoke.buff");
        assert!(files[0].1.contains("@test"));
    }

    #[test]
    fn example_gen_produces_one_file() {
        let files = files_for_gen(GenKind::Example, "demo");
        assert_eq!(files.len(), 1);
        assert_eq!(files[0].0, "examples/demo.buff");
        assert!(files[0].1.contains("func main():"));
    }

    #[test]
    fn module_stub_exports_placeholder() {
        let s = render_module_stub("user");
        assert!(s.contains("export func placeholder()"), "stub: {s}");
    }

    #[test]
    fn module_test_stub_imports_placeholder() {
        let s = render_module_test_stub("user");
        assert!(s.contains("import { placeholder }"), "stub: {s}");
        assert!(s.contains("src/modules/user"), "stub: {s}");
    }
}
