//! `buff generate <TEMPLATE>` — boilerplate template generator (T103).
//!
//! Like `cargo generate` but for Buff-specific patterns. Four built-in
//! templates are available as string constants with `{{NAME}}` substitution:
//!
//! - `gpu_kernel` — GPU-dispatched function with `@prefer(gpu)` + WGSL scaffold.
//! - `web_handler` — Web.get/post handler with JSON response.
//! - `data_pipeline` — Source → filter → Sink pipeline.
//! - `cli_app` — CLI app with argument parsing.
//!
//! Use `buff generate --list` to print available templates.
//! Use `buff generate <TEMPLATE> --name <NAME> --output <PATH>` to generate.

use std::collections::BTreeMap;
use std::fs;
use std::path::PathBuf;

use anyhow::{bail, Context, Result};

/// A built-in template with its name, description, and content.
struct Template {
    name: &'static str,
    description: &'static str,
    content: &'static str,
}

/// All built-in templates, keyed by name.
fn builtin_templates() -> BTreeMap<&'static str, Template> {
    let mut m = BTreeMap::new();
    m.insert(
        "gpu_kernel",
        Template {
            name: "gpu_kernel",
            description: "GPU-dispatched function with @prefer(gpu) + WGSL scaffold",
            content: GPU_KERNEL_TEMPLATE,
        },
    );
    m.insert(
        "web_handler",
        Template {
            name: "web_handler",
            description: "Web.get/post handler with JSON response",
            content: WEB_HANDLER_TEMPLATE,
        },
    );
    m.insert(
        "data_pipeline",
        Template {
            name: "data_pipeline",
            description: "Source → filter → Sink pipeline",
            content: DATA_PIPELINE_TEMPLATE,
        },
    );
    m.insert(
        "cli_app",
        Template {
            name: "cli_app",
            description: "CLI app with argument parsing",
            content: CLI_APP_TEMPLATE,
        },
    );
    m
}

/// Print the list of available templates to stderr.
pub fn print_template_list() {
    let templates = builtin_templates();
    eprintln!("Available templates:");
    for t in templates.values() {
        eprintln!("  {:<20} {}", t.name, t.description);
    }
}

/// Entry point for `buff generate <TEMPLATE>`.
///
/// When `--list` is set, prints available templates and returns.
/// Otherwise resolves the template, substitutes `{{NAME}}`, and writes
/// the output file.
pub fn run(template: &str, name: &str, output: Option<PathBuf>) -> Result<()> {
    let templates = builtin_templates();

    let t = templates.get(template).ok_or_else(|| {
        anyhow::Error::msg(format!(
            "unknown template `{template}` (use `buff generate --list` to see available templates)"
        ))
    })?;

    // Determine the substitution name: use `--name` if provided, else
    // fall back to the template name.
    let sub_name = if name.is_empty() { template } else { name };

    // Substitute {{NAME}} in the template content.
    let content = t.content.replace("{{NAME}}", sub_name);

    // Determine the output path.
    let out_path = match output {
        Some(p) => p,
        None => PathBuf::from(format!("{sub_name}.buff")),
    };

    // Refuse to clobber.
    if out_path.exists() {
        bail!(
            "refusing to overwrite existing file `{}` \
             (delete it first if you want to regenerate)",
            out_path.display()
        );
    }

    // Write the output file.
    if let Some(parent) = out_path.parent() {
        if !parent.as_os_str().is_empty() {
            fs::create_dir_all(parent)
                .with_context(|| format!("failed to create directory `{}`", parent.display()))?;
        }
    }
    fs::write(&out_path, &content)
        .with_context(|| format!("failed to write `{}`", out_path.display()))?;

    eprintln!(
        "Generated `{}` from template `{template}`.",
        out_path.display()
    );
    Ok(())
}

// ---------------------------------------------------------------------------
// Built-in template strings
// ---------------------------------------------------------------------------

/// GPU-dispatched kernel with `@prefer(gpu)` hint + WGSL scaffold.
const GPU_KERNEL_TEMPLATE: &str = r#"// {{NAME}} — GPU-dispatched kernel (generated by `buff generate gpu_kernel`)
// Run with: buff run {{NAME}}.buff

@prefer(gpu)
func compute_kernel(input: Vector<f64]) -> Vector<f64]:
    let n = input.len()
    let result = Vector<f64>.new(n)

    for i in 0..n:
        // Element-wise computation — the runtime dispatches this
        // loop to the GPU when the @prefer(gpu) hint is present
        // and a GPU is available.
        result[i] = input[i] * input[i] + 1.0

    return result

func main():
    let data = Vector<f64>.from([1.0, 2.0, 3.0, 4.0, 5.0])
    let output = compute_kernel(data)
    print("Result: {output}")
"#;

/// Web handler with GET/POST routes and JSON response.
const WEB_HANDLER_TEMPLATE: &str = r#"// {{NAME}} — web handler (generated by `buff generate web_handler`)
// Run with: buff run {{NAME}}.buff

import { Web } from "buff-web"

struct Greeting:
    message: String
    count: int

func main():
    let app = Web.new()

    app.get("/hello", fn(req: Web.Request) -> Web.Response:
        let name = req.query.get("name", "world")
        return Web.Response.json(Greeting {
            message: "Hello, {name}!",
            count: 1,
        })
    )

    app.post("/echo", fn(req: Web.Request) -> Web.Response:
        let body = req.body
        return Web.Response.json(body)
    )

    app.listen(8080)
    print("{{NAME}} listening on http://localhost:8080")
"#;

/// Data pipeline: Source → filter → Sink.
const DATA_PIPELINE_TEMPLATE: &str = r#"// {{NAME}} — data pipeline (generated by `buff generate data_pipeline`)
// Run with: buff run {{NAME}}.buff

import { Pipeline, Source, Sink } from "buff-pipeline"

struct Record:
    id: int
    value: f64
    label: String

func main():
    // Build a pipeline: Source → filter → transform → Sink
    let pipeline = Pipeline.new()
        .source(Source.from_iter([
            Record { id: 1, value: 10.0, label: "alpha" },
            Record { id: 2, value: 20.0, label: "beta" },
            Record { id: 3, value: 30.0, label: "gamma" },
        ]))
        .filter(fn(r: Record) -> bool:
            return r.value > 15.0
        })
        .map(fn(r: Record) -> Record:
            return Record {
                id: r.id,
                value: r.value * 2.0,
                label: r.label,
            }
        })
        .sink(Sink.to_stdout())

    pipeline.run()
    print("{{NAME}} pipeline completed.")
"#;

/// CLI app with argument parsing.
const CLI_APP_TEMPLATE: &str = r#"// {{NAME}} — CLI app (generated by `buff generate cli_app`)
// Run with: buff run {{NAME}}.buff -- <args>

import { Cli } from "buff-cli"

func main():
    let app = Cli.new("{{NAME}}", "A CLI app generated from the cli_app template")

    app.arg("input", "Input file path", required: true)
    app.arg("--verbose", "Enable verbose output", flag: true)
    app.arg("--count", "Number of iterations", default: "10")

    let args = app.parse()

    let input = args.get("input")
    let verbose = args.has("--verbose")
    let count = args.get("--count").parse_int()

    if verbose:
        print("{{NAME}} v1.0.0")
        print("input: {input}, count: {count}")

    for i in 0..count:
        print("Processing {input} — iteration {i + 1}")

    print("Done.")
"#;

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn builtin_templates_has_four_entries() {
        let templates = builtin_templates();
        assert_eq!(templates.len(), 4);
        assert!(templates.contains_key("gpu_kernel"));
        assert!(templates.contains_key("web_handler"));
        assert!(templates.contains_key("data_pipeline"));
        assert!(templates.contains_key("cli_app"));
    }

    #[test]
    fn gpu_kernel_template_contains_name_placeholder() {
        assert!(GPU_KERNEL_TEMPLATE.contains("{{NAME}}"));
    }

    #[test]
    fn web_handler_template_contains_name_placeholder() {
        assert!(WEB_HANDLER_TEMPLATE.contains("{{NAME}}"));
    }

    #[test]
    fn data_pipeline_template_contains_name_placeholder() {
        assert!(DATA_PIPELINE_TEMPLATE.contains("{{NAME}}"));
    }

    #[test]
    fn cli_app_template_contains_name_placeholder() {
        assert!(CLI_APP_TEMPLATE.contains("{{NAME}}"));
    }

    #[test]
    fn substitution_replaces_name() {
        let content = GPU_KERNEL_TEMPLATE.replace("{{NAME}}", "my_kernel");
        assert!(content.contains("my_kernel"));
        assert!(!content.contains("{{NAME}}"));
    }

    #[test]
    fn unknown_template_returns_error() {
        let templates = builtin_templates();
        assert!(!templates.contains_key("nonexistent"));
    }

    #[test]
    fn print_template_list_does_not_panic() {
        // Just verify it runs without panicking.
        print_template_list();
    }
}
