[package]
name = "buff-lang-codegen-buffhtml"
version = "1.0.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
thiserror.workspace = true
buff-lang-error.workspace = true
buff-lang-ast-rsx.workspace = true
syn.workspace = true
quote.workspace = true
proc-macro2.workspace = true
prettyplease.workspace = true

[dev-dependencies]
buff-lang-buffhtml-parser.workspace = true
insta.workspace = true
