[package]
name = "bufflings"
version = "1.0.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[[bin]]
name = "bufflings"
path = "src/main.rs"

[lib]
name = "bufflings"
path = "src/lib.rs"

[dependencies]
clap.workspace = true
anyhow.workspace = true
thiserror.workspace = true
serde.workspace = true
toml.workspace = true
tokio.workspace = true
notify.workspace = true
dirs.workspace = true
