/* ==========================================================================
   Buff Playground — main script
   ==========================================================================
   Wires:
     - Wasm module (./pkg/buff_playground.js, generated by wasm-bindgen)
     - CodeMirror editor (CDN-loaded in index.html)
     - 300ms debounced transpile → renders Rust output or error message
     - URL share-by-fragment: base64-encode source into `#`, restore on load
     - Example picker dropdown
     - Status pill (idle/working/ok/error)
   ========================================================================== */

import init, { transpile } from "./pkg/buff_playground.js";

// ----- DOM references ---------------------------------------------------
const editorEl = document.getElementById("editor");
const outputCodeEl = document.getElementById("output-code");
const outputPaneEl = document.querySelector(".pane-output");
const outputHeaderEl = document.getElementById("output-header");
const outputMetaEl = document.getElementById("output-meta");
const inputMetaEl = document.getElementById("input-meta");
const footerEl = document.getElementById("status-bar");
const statusTextEl = document.getElementById("status-text");
const statusMessageEl = document.getElementById("status-message");
const shareBtn = document.getElementById("share-btn");
const examplePicker = document.getElementById("example-picker");
const exampleMenu = document.getElementById("example-menu");
const bodyEl = document.body;

// ----- Constants --------------------------------------------------------
const DEBOUNCE_MS = 300;
const URL_FRAGMENT_PREFIX = "s="; // fragment shape: #s=<base64>

// ----- Examples (kept inline so the playground works fully offline once
//        the Wasm is fetched; no second round-trip for examples). ---------
const EXAMPLES = {
    fibonacci:
        "// recursive fibonacci\n" +
        "func fib(n: Int) -> Int:\n" +
        "    if n < 2:\n" +
        "        return n\n" +
        "    return fib(n - 1) + fib(n - 2)\n" +
        "\n" +
        "func main():\n" +
        "    let n = 10\n" +
        "    print(fib(n))\n",
    ola:
        "// Olá, Buff! — first example\n" +
        "func main():\n" +
        "    print(\"Olá, Buff!\")\n",
    calculadora:
        "// simple arithmetic\n" +
        "func add(a: Int, b: Int) -> Int:\n" +
        "    return a + b\n" +
        "\n" +
        "func main():\n" +
        "    print(add(2, 3))\n",
    error_demo:
        "// triggers a parse error — watch the status rail\n" +
        "func ( broken\n",
};

// ----- CodeMirror instance ---------------------------------------------
// Rust mode is close enough to Buff for highlighting (keywords overlap:
// func→fn-ish, let, return, if, else, match...). Buff's 25 keywords are a
// subset of Rust's surface syntax; we accept the imperfect mapping rather
// than ship a custom CodeMirror mode.
const editor = CodeMirror.fromTextArea(editorEl, {
    mode: "text/x-rustsrc",
    theme: "material-darker",
    lineNumbers: true,
    lineWrapping: false,
    indentUnit: 4,
    tabSize: 4,
    indentWithTabs: false,
    matchBrackets: true,
    autoCloseBrackets: true,
    styleActiveLine: true,
    extraKeys: {
        // Soft-tabs (Buff rejects hard tabs in source — keep editor honest).
        "Tab": (cm) => cm.replaceSelection("    ", "end"),
        // Ctrl/Cmd-Enter: transpile immediately (skip debounce).
        "Cmd-Enter": transpileNow,
        "Ctrl-Enter": transpileNow,
    },
});

// ----- State ------------------------------------------------------------
let debounceTimer = null;
let lastTranspileResult = null;

// ----- Helpers ----------------------------------------------------------

/** Set the status pill + footer message. Status ∈ {idle, working, ok, error}. */
function setStatus(status, message) {
    footerEl.dataset.status = status;
    statusTextEl.textContent = status;
    if (message === undefined) {
        switch (status) {
            case "idle":   message = "ready"; break;
            case "working": message = "transpiling…"; break;
            case "ok":     message = "transpile ok"; break;
            case "error":  message = lastTranspileResult?.error ?? "error"; break;
        }
    }
    statusMessageEl.textContent = message;
}

/** Render the Rust source into the output pane. */
function renderRust(rustSource) {
    outputCodeEl.textContent = rustSource;
    outputPaneEl.dataset.state = "ok";
    outputMetaEl.textContent = `${rustSource.split("\n").length} lines`;
    // Trigger the success pulse animation by re-adding the class.
    outputHeaderEl.classList.remove("flash-ok");
    void outputHeaderEl.offsetWidth; // reflow to restart animation
    outputHeaderEl.classList.add("flash-ok");
}

/** Render an error: caret-equivalent message in status + crimson output header. */
function renderError(errorText, line, col) {
    outputCodeEl.textContent = "";
    outputPaneEl.dataset.state = "error";
    const positionSuffix = (line && col) ? `  @  ${line}:${col}` : "";
    outputMetaEl.textContent = "error" + positionSuffix;
}

/** Core: run the wasm transpile and dispatch the result. */
function runTranspile(source) {
    let resultText;
    try {
        resultText = transpile(source);
    } catch (err) {
        // The wasm boundary should never throw (panics caught by hook),
        // but defend against transport-level issues anyway.
        lastTranspileResult = { ok: false, error: `internal: ${String(err)}` };
        setStatus("error", lastTranspileResult.error);
        renderError(lastTranspileResult.error);
        return;
    }

    let result;
    try {
        result = JSON.parse(resultText);
    } catch (err) {
        lastTranspileResult = { ok: false, error: `wire: invalid JSON from wasm: ${err}` };
        setStatus("error", lastTranspileResult.error);
        renderError(lastTranspileResult.error);
        return;
    }

    lastTranspileResult = result;
    if (result.ok) {
        renderRust(result.rust);
        setStatus("ok");
        // Refresh URL fragment lazily (debounced by same timer — keep URL stable).
        updateUrlFragment(source);
        // Update input meta with byte count.
        inputMetaEl.textContent = `${new Blob([source]).size} bytes`;
    } else {
        renderError(result.error, result.line, result.col);
        setStatus("error", result.error);
    }
}

/** Debounced transpile entry — schedules a run after DEBOUNCE_MS idle. */
function scheduleTranspile() {
    setStatus("working");
    if (debounceTimer !== null) clearTimeout(debounceTimer);
    debounceTimer = window.setTimeout(() => {
        debounceTimer = null;
        runTranspile(editor.getValue());
    }, DEBOUNCE_MS);
}

/** Skip debounce — used by Ctrl/Cmd-Enter. */
function transpileNow() {
    if (debounceTimer !== null) {
        clearTimeout(debounceTimer);
        debounceTimer = null;
    }
    runTranspile(editor.getValue());
}

// ----- URL share-by-fragment -------------------------------------------

/** UTF-8-safe base64 encode (handles Olá, emoji, etc.). */
function encodeBase64(text) {
    const bytes = new TextEncoder().encode(text);
    // Binary → base64 in chunks (avoid String.fromCharCode apply limits).
    let binary = "";
    const chunkSize = 0x8000;
    for (let i = 0; i < bytes.length; i += chunkSize) {
        const chunk = bytes.subarray(i, i + chunkSize);
        binary += String.fromCharCode.apply(null, chunk);
    }
    return btoa(binary);
}

/** UTF-8-safe base64 decode. Returns the original string. */
function decodeBase64(b64) {
    const binary = atob(b64);
    const bytes = new Uint8Array(binary.length);
    for (let i = 0; i < binary.length; i++) bytes[i] = binary.charCodeAt(i);
    return new TextDecoder().decode(bytes);
}

/** Encode source into the URL fragment (#s=<base64>). */
function updateUrlFragment(source) {
    try {
        const encoded = encodeBase64(source);
        const newHash = `#${URL_FRAGMENT_PREFIX}${encoded}`;
        // Only update if changed — avoids spamming history on every keystroke.
        if (location.hash !== newHash) {
            history.replaceState(null, "", newHash);
        }
    } catch (err) {
        // Most likely source too large for URL (browser limit ~2KB safe).
        // Silently skip — the playground still works, just no share URL.
        console.warn("[buff] could not update URL fragment:", err);
    }
}

/** On page load: read URL fragment and restore source if present. */
function sourceFromUrlFragment() {
    const hash = location.hash;
    if (!hash || !hash.startsWith(`#${URL_FRAGMENT_PREFIX}`)) return null;
    const encoded = hash.slice(`#${URL_FRAGMENT_PREFIX}`.length);
    if (encoded.length === 0) return null;
    try {
        return decodeBase64(encoded);
    } catch (err) {
        console.warn("[buff] could not decode URL fragment:", err);
        return null;
    }
}

// ----- Example picker ---------------------------------------------------
function closeExampleMenu() {
    exampleMenu.hidden = true;
    examplePicker.setAttribute("aria-expanded", "false");
}

function openExampleMenu() {
    exampleMenu.hidden = false;
    examplePicker.setAttribute("aria-expanded", "true");
}

examplePicker.addEventListener("click", (e) => {
    e.stopPropagation();
    if (exampleMenu.hidden) openExampleMenu();
    else closeExampleMenu();
});

document.addEventListener("click", (e) => {
    if (!exampleMenu.hidden && !exampleMenu.contains(e.target) && e.target !== examplePicker) {
        closeExampleMenu();
    }
});

document.addEventListener("keydown", (e) => {
    if (e.key === "Escape" && !exampleMenu.hidden) closeExampleMenu();
});

exampleMenu.querySelectorAll(".example-item").forEach((btn) => {
    btn.addEventListener("click", () => {
        const key = btn.dataset.example;
        const src = EXAMPLES[key];
        if (typeof src === "string") {
            editor.setValue(src);
            // Mark the chosen example as checked in the menu.
            exampleMenu.querySelectorAll(".example-item").forEach((b) => {
                b.setAttribute("aria-checked", b === btn ? "true" : "false");
            });
            transpileNow();
        }
        closeExampleMenu();
    });
});

// ----- Share button -----------------------------------------------------
shareBtn.addEventListener("click", async () => {
    // Ensure URL has the latest source.
    updateUrlFragment(editor.getValue());
    const url = location.href;
    try {
        await navigator.clipboard.writeText(url);
        setStatus("ok", "share link copied to clipboard");
        // Bounce back to ok/error after a moment.
        window.setTimeout(() => {
            setStatus(lastTranspileResult && lastTranspileResult.ok ? "ok" : "error");
        }, 1800);
    } catch (err) {
        // Clipboard API may be blocked — fall back to selecting the URL bar.
        setStatus("error", `share: could not copy — copy from the URL bar (${err})`);
    }
});

// ----- Editor change handler (debounced) -------------------------------
editor.on("change", () => {
    // Clear any "picked" example checkmark — user is typing.
    exampleMenu.querySelectorAll(".example-item").forEach((b) => {
        b.setAttribute("aria-checked", "false");
    });
    scheduleTranspile();
});

// ----- Boot -------------------------------------------------------------
async function boot() {
    try {
        await init();
    } catch (err) {
        setStatus("error", `failed to load wasm: ${err}`);
        return;
    }

    // Mark page as ready — removes the loading reveal animation.
    bodyEl.dataset.state = "ready";

    // Restore from URL fragment, else load the default example.
    const restored = sourceFromUrlFragment();
    if (restored !== null) {
        editor.setValue(restored);
        // Mark the corresponding example as checked (if it matches one).
        const matchKey = Object.keys(EXAMPLES).find((k) => EXAMPLES[k] === restored);
        if (matchKey) {
            exampleMenu.querySelector(`[data-example="${matchKey}"]`)
                ?.setAttribute("aria-checked", "true");
        }
    } else {
        editor.setValue(EXAMPLES.fibonacci);
        exampleMenu.querySelector('[data-example="fibonacci"]')
            ?.setAttribute("aria-checked", "true");
    }

    // First transpile (skip debounce — instant feedback on load).
    transpileNow();

    // Give editor focus so the user can start typing immediately.
    editor.focus();
}

boot();
