/* ==========================================================================
   Buff Playground — main script
   ==========================================================================
   Wires:
     - Wasm module (./pkg/buff_playground.js, generated by wasm-bindgen)
     - CodeMirror editor (CDN-loaded in index.html)
     - 300ms debounced transpile → renders Rust output or error message
     - URL share-by-fragment: base64-encode source into `#`, restore on load
     - Example picker dropdown
     - Status pill (idle/working/ok/error)
   ========================================================================== */

import init, { transpile } from "./pkg/buff_playground.js";

// ----- DOM references ---------------------------------------------------
const editorEl = document.getElementById("editor");
const outputCodeEl = document.getElementById("output-code");
const outputPaneEl = document.querySelector(".pane-output");
const outputHeaderEl = document.getElementById("output-header");
const outputMetaEl = document.getElementById("output-meta");
const inputMetaEl = document.getElementById("input-meta");
const footerEl = document.getElementById("status-bar");
const statusTextEl = document.getElementById("status-text");
const statusMessageEl = document.getElementById("status-message");
const shareBtn = document.getElementById("share-btn");
const examplePicker = document.getElementById("example-picker");
const exampleMenu = document.getElementById("example-menu");
const bodyEl = document.body;

// ----- Constants --------------------------------------------------------
const DEBOUNCE_MS = 300;
const URL_FRAGMENT_PREFIX = "s="; // fragment shape: #s=<base64>

// ----- Examples (kept inline so the playground works fully offline once
//        the Wasm is fetched; no second round-trip for examples). ---------
//
//        Categories:
//          • basics — the v0.1/v0.5 evergreen examples
//          • v1.25  — new language + stdlib surface shipped in the launch-
//                     readiness waves (generics, ranges, raw strings, defer,
//                     Http / Json prelude types, …). Each snippet is a
//                     transpile-only demo; some lower to crates that the
//                     single-file rustc pipeline cannot LINK (Http/Json
//                     reach into reqwest/serde_json), but the generated
//                     Rust IS the demo. See README "What it does NOT do".
const EXAMPLES = {
    // ─── Basics ───────────────────────────────────────────────────────
    fibonacci:
        "// recursive fibonacci\n" +
        "func fib(n: Int) -> Int:\n" +
        "    if n < 2:\n" +
        "        return n\n" +
        "    return fib(n - 1) + fib(n - 2)\n" +
        "\n" +
        "func main():\n" +
        "    let n = 10\n" +
        "    print(fib(n))\n",
    ola:
        "// Olá, Buff! — first example\n" +
        "func main():\n" +
        "    print(\"Olá, Buff!\")\n",
    calculadora:
        "// simple arithmetic\n" +
        "func add(a: Int, b: Int) -> Int:\n" +
        "    return a + b\n" +
        "\n" +
        "func main():\n" +
        "    print(add(2, 3))\n",
    error_demo:
        "// triggers a parse error — watch the status rail\n" +
        "func ( broken\n",

    // ─── v1.25 language features ───────────────────────────────────────
    // Generics (T13): user-defined generic types + functions. rustc
    // monomorphizes each call site — zero-cost static dispatch.
    generics:
        "// v1.25 — generics + monomorphization (T13)\n" +
        "//\n" +
        "// rustc generates a fresh copy of `id` per call site: `id::<i64>`\n" +
        "// and `id::<&str>`. No type erasure, no vtable — pure static dispatch.\n" +
        "//\n" +
        "// Brace form for the generic struct — the documented & tested shape\n" +
        "// from the T13 acceptance criteria.\n" +
        "\n" +
        "struct Pair<T, U> { x: T, y: U }\n" +
        "\n" +
        "func id<T>(x: T) -> T:\n" +
        "    return x\n" +
        "\n" +
        "func main():\n" +
        "    let p = Pair.new(x: 42, y: \"hello\")\n" +
        "    let n = id(42)\n" +
        "    let s = id(\"hello\")\n" +
        "    print(p.x)\n" +
        "    print(p.y)\n" +
        "    print(n)\n" +
        "    print(s)\n",

    // Range syntax (T84): `a..b` exclusive + `a..=b` inclusive. Ranges
    // are LAZY iterators (Rust std::ops::Range / RangeInclusive).
    range:
        "// v1.25 — range syntax (T84)\n" +
        "//\n" +
        "// `a..b`  — exclusive (excludes b)\n" +
        "// `a..=b` — inclusive (includes b)\n" +
        "// Both are LAZY iterators: no allocation, O(1) `.contains()`.\n" +
        "\n" +
        "func main():\n" +
        "    print(\"exclusive 0..5:\")\n" +
        "    for i in 0..5:\n" +
        "        print(i)\n" +
        "\n" +
        "    print(\"inclusive 0..=5:\")\n" +
        "    for i in 0..=5:\n" +
        "        print(i)\n" +
        "\n" +
        "    if (0..10).contains(5):\n" +
        "        print(\"5 is in 0..10\")\n" +
        "\n" +
        "    let n = 3\n" +
        "    for i in 0..n * 2:\n" +
        "        print(i)\n",

    // Pattern matching (T39/T40/T41 + T27 exhaustiveness): or-patterns,
    // guards, struct patterns. Built-in Option<T> / Result<T, E> arms.
    pattern_matching:
        "// v1.25 — pattern matching (T27/T39/T40/T41)\n" +
        "//\n" +
        "// Exhaustive match over Option<T> + Result<T, E>. v1.25 also adds\n" +
        "// or-patterns (`A | B`), guards (`if cond`), and struct patterns\n" +
        "// (T39/T40/T41).\n" +
        "\n" +
        "func classify(n: Int) -> Int:\n" +
        "    if n == 0:\n" +
        "        return 100\n" +
        "    return 999\n" +
        "\n" +
        "func lookup(id: Int) -> Result<Int, Error>:\n" +
        "    if id == 1:\n" +
        "        return Ok(111)\n" +
        "    return Error(\"not found\")\n" +
        "\n" +
        "func main():\n" +
        "    let mut drawer = [11, 22, 33]\n" +
        "    let taken = drawer.pop()\n" +
        "    match taken { Some(x) => print(x), None => print(0) }\n" +
        "\n" +
        "    let found = lookup(1)\n" +
        "    match found { Ok(v) => print(v), Err(_) => print(0) }\n" +
        "\n" +
        "    let missing = lookup(99)\n" +
        "    match missing { Ok(v) => print(v), Err(_) => print(0) }\n",

    // Raw strings (T93): `r"..."` and `r#"..."#` (Rust-style). Backslashes
    // and braces are literal — no escape processing, no interpolation.
    raw_strings:
        "// v1.25 — raw string literals (T93)\n" +
        "//\n" +
        "// `r\"...\"`     — backslashes and braces are literal\n" +
        "// `r#\"...\"#`   — N hashes let `\"` appear inside the string\n" +
        "//\n" +
        "// Perfect for embedding regex / JSON / shell globs without\n" +
        "// escaping every metacharacter.\n" +
        "\n" +
        "func main():\n" +
        "    let re = r\"\\d+\\.\\d+\"\n" +
        "    let json = r#\"{\"name\": \"Buff\", \"version\": 1.25}\"#\n" +
        "    let path = r\"C:\\Users\\buff\\playground\"\n" +
        "    print(re)\n" +
        "    print(json)\n" +
        "    print(path)\n",

    // Defer statement (T100): schedule cleanup at function exit. Multiple
    // defers run LIFO. Codegen emits them at EVERY return point.
    defer:
        "// v1.25 — defer statement (T100)\n" +
        "//\n" +
        "// `defer EXPR` schedules EXPR to run when the enclosing FUNCTION\n" +
        "// exits, on ANY exit path (explicit `return` or implicit fall-\n" +
        "// through). Multiple defers run LIFO (last-registered first).\n" +
        "// The borrow checker never sees them — Buff hides the choreography.\n" +
        "\n" +
        "func process(label: String):\n" +
        "    print(\"opening \" + label)\n" +
        "    defer print(\"closing \" + label)\n" +
        "    print(\"working with \" + label)\n" +
        "    if label == \"skip\":\n" +
        "        return\n" +
        "    print(\"more work\")\n" +
        "\n" +
        "func main():\n" +
        "    process(\"file-a\")\n" +
        "    print(\"---\")\n" +
        "    process(\"skip\")\n",

    // ─── v1.25 stdlib prelude types ────────────────────────────────────
    // Http (T80): blocking GET/POST via reqwest::blocking. The generated
    // Rust references `reqwest` (recorded in codegen `extern_crates`) —
    // single-file rustc cannot LINK it, but the lowered Rust IS the demo.
    // NOTE: raw strings (T93) for the JSON body — Buff treats `{` in
    // regular strings as interpolation. The r#"..."# form is needed when
    // the payload itself contains `"`.
    http_client:
        "// v1.25 — Http prelude type (T80)\n" +
        "//\n" +
        "// Http.get(url)  — blocking GET, returns String body\n" +
        "// Http.post(u,b) — blocking POST with a String body\n" +
        "//\n" +
        "// Lowers to reqwest::blocking — the generated Rust references the\n" +
        "// reqwest crate (registered in codegen extern_crates). The single-\n" +
        "// file rustc pipeline cannot LINK external crates, but the lowered\n" +
        "// Rust on the right IS the demo — see how clean the call site is\n" +
        "// compared to reqwest's verbose Rust surface.\n" +
        "//\n" +
        "// The POST body uses a raw string (T93): Buff's regular strings\n" +
        "// treat `{` as interpolation; raw strings are literal. The r#\"...\"#\n" +
        "// form lets `\"` appear inside the payload.\n" +
        "\n" +
        "func main():\n" +
        "    let body = Http.get(\"https://example.com\")\n" +
        "    print(body)\n" +
        "\n" +
        "    let json = r#\"{\"hi\": 1}\"#\n" +
        "    let reply = Http.post(\"https://httpbin.org/post\", json)\n" +
        "    print(reply)\n",

    // Json (T23): parse + stringify via serde_json. Same namespace shape
    // as Toml / Yaml / Csv — heterogeneous Map round-trip, never panics.
    // Uses a raw string for the JSON payload (see http_client note above).
    json:
        "// v1.25 — Json prelude type (T23)\n" +
        "//\n" +
        "// Json.parse(s)     — parse JSON text into a Buff Map (NEVER panics;\n" +
        "//                    malformed input → empty Map)\n" +
        "// Json.stringify(v) — serialize a Map back to JSON text\n" +
        "//\n" +
        "// Lowers to serde_json — recorded in codegen extern_crates. The\n" +
        "// right pane shows the generated Rust; the parse/stringify call\n" +
        "// sites use unwrap_or_default() so the surface is panic-free.\n" +
        "//\n" +
        "// Raw string for the payload — Buff's regular strings interpolate\n" +
        "// `{...}`, but JSON is full of braces. r#\"...\"# is the clean way\n" +
        "// to embed JSON in Buff (the # hashes let `\"` appear literally).\n" +
        "\n" +
        "func main():\n" +
        "    let payload = r#\"{\"name\":\"Buff\",\"version\":1.25}\"#\n" +
        "    let data = Json.parse(payload)\n" +
        "    print(data)\n" +
        "\n" +
        "    let back = Json.stringify(data)\n" +
        "    print(back)\n",
};

// ----- CodeMirror instance ---------------------------------------------
// Rust mode is close enough to Buff for highlighting (keywords overlap:
// func→fn-ish, let, return, if, else, match...). Buff's 25 keywords are a
// subset of Rust's surface syntax; we accept the imperfect mapping rather
// than ship a custom CodeMirror mode.
const editor = CodeMirror.fromTextArea(editorEl, {
    mode: "text/x-rustsrc",
    theme: "material-darker",
    lineNumbers: true,
    lineWrapping: false,
    indentUnit: 4,
    tabSize: 4,
    indentWithTabs: false,
    matchBrackets: true,
    autoCloseBrackets: true,
    styleActiveLine: true,
    extraKeys: {
        // Soft-tabs (Buff rejects hard tabs in source — keep editor honest).
        "Tab": (cm) => cm.replaceSelection("    ", "end"),
        // Ctrl/Cmd-Enter: transpile immediately (skip debounce).
        "Cmd-Enter": transpileNow,
        "Ctrl-Enter": transpileNow,
    },
});

// ----- State ------------------------------------------------------------
let debounceTimer = null;
let lastTranspileResult = null;

// ----- Helpers ----------------------------------------------------------

/** Set the status pill + footer message. Status ∈ {idle, working, ok, error}. */
function setStatus(status, message) {
    footerEl.dataset.status = status;
    statusTextEl.textContent = status;
    if (message === undefined) {
        switch (status) {
            case "idle":   message = "ready"; break;
            case "working": message = "transpiling…"; break;
            case "ok":     message = "transpile ok"; break;
            case "error":  message = lastTranspileResult?.error ?? "error"; break;
        }
    }
    statusMessageEl.textContent = message;
}

/** Render the Rust source into the output pane. */
function renderRust(rustSource) {
    outputCodeEl.textContent = rustSource;
    outputPaneEl.dataset.state = "ok";
    outputMetaEl.textContent = `${rustSource.split("\n").length} lines`;
    // Trigger the success pulse animation by re-adding the class.
    outputHeaderEl.classList.remove("flash-ok");
    void outputHeaderEl.offsetWidth; // reflow to restart animation
    outputHeaderEl.classList.add("flash-ok");
}

/** Render an error: caret-equivalent message in status + crimson output header. */
function renderError(errorText, line, col) {
    outputCodeEl.textContent = "";
    outputPaneEl.dataset.state = "error";
    const positionSuffix = (line && col) ? `  @  ${line}:${col}` : "";
    outputMetaEl.textContent = "error" + positionSuffix;
}

/** Core: run the wasm transpile and dispatch the result. */
function runTranspile(source) {
    let resultText;
    try {
        resultText = transpile(source);
    } catch (err) {
        // The wasm boundary should never throw (panics caught by hook),
        // but defend against transport-level issues anyway.
        lastTranspileResult = { ok: false, error: `internal: ${String(err)}` };
        setStatus("error", lastTranspileResult.error);
        renderError(lastTranspileResult.error);
        return;
    }

    let result;
    try {
        result = JSON.parse(resultText);
    } catch (err) {
        lastTranspileResult = { ok: false, error: `wire: invalid JSON from wasm: ${err}` };
        setStatus("error", lastTranspileResult.error);
        renderError(lastTranspileResult.error);
        return;
    }

    lastTranspileResult = result;
    if (result.ok) {
        renderRust(result.rust);
        setStatus("ok");
        // Refresh URL fragment lazily (debounced by same timer — keep URL stable).
        updateUrlFragment(source);
        // Update input meta with byte count.
        inputMetaEl.textContent = `${new Blob([source]).size} bytes`;
    } else {
        renderError(result.error, result.line, result.col);
        setStatus("error", result.error);
    }
}

/** Debounced transpile entry — schedules a run after DEBOUNCE_MS idle. */
function scheduleTranspile() {
    setStatus("working");
    if (debounceTimer !== null) clearTimeout(debounceTimer);
    debounceTimer = window.setTimeout(() => {
        debounceTimer = null;
        runTranspile(editor.getValue());
    }, DEBOUNCE_MS);
}

/** Skip debounce — used by Ctrl/Cmd-Enter. */
function transpileNow() {
    if (debounceTimer !== null) {
        clearTimeout(debounceTimer);
        debounceTimer = null;
    }
    runTranspile(editor.getValue());
}

// ----- URL share-by-fragment -------------------------------------------

/** UTF-8-safe base64 encode (handles Olá, emoji, etc.). */
function encodeBase64(text) {
    const bytes = new TextEncoder().encode(text);
    // Binary → base64 in chunks (avoid String.fromCharCode apply limits).
    let binary = "";
    const chunkSize = 0x8000;
    for (let i = 0; i < bytes.length; i += chunkSize) {
        const chunk = bytes.subarray(i, i + chunkSize);
        binary += String.fromCharCode.apply(null, chunk);
    }
    return btoa(binary);
}

/** UTF-8-safe base64 decode. Returns the original string. */
function decodeBase64(b64) {
    const binary = atob(b64);
    const bytes = new Uint8Array(binary.length);
    for (let i = 0; i < binary.length; i++) bytes[i] = binary.charCodeAt(i);
    return new TextDecoder().decode(bytes);
}

/** Encode source into the URL fragment (#s=<base64>). */
function updateUrlFragment(source) {
    try {
        const encoded = encodeBase64(source);
        const newHash = `#${URL_FRAGMENT_PREFIX}${encoded}`;
        // Only update if changed — avoids spamming history on every keystroke.
        if (location.hash !== newHash) {
            history.replaceState(null, "", newHash);
        }
    } catch (err) {
        // Most likely source too large for URL (browser limit ~2KB safe).
        // Silently skip — the playground still works, just no share URL.
        console.warn("[buff] could not update URL fragment:", err);
    }
}

/** On page load: read URL fragment and restore source if present. */
function sourceFromUrlFragment() {
    const hash = location.hash;
    if (!hash || !hash.startsWith(`#${URL_FRAGMENT_PREFIX}`)) return null;
    const encoded = hash.slice(`#${URL_FRAGMENT_PREFIX}`.length);
    if (encoded.length === 0) return null;
    try {
        return decodeBase64(encoded);
    } catch (err) {
        console.warn("[buff] could not decode URL fragment:", err);
        return null;
    }
}

// ----- Example picker ---------------------------------------------------
function closeExampleMenu() {
    exampleMenu.hidden = true;
    examplePicker.setAttribute("aria-expanded", "false");
}

function openExampleMenu() {
    exampleMenu.hidden = false;
    examplePicker.setAttribute("aria-expanded", "true");
}

examplePicker.addEventListener("click", (e) => {
    e.stopPropagation();
    if (exampleMenu.hidden) openExampleMenu();
    else closeExampleMenu();
});

document.addEventListener("click", (e) => {
    if (!exampleMenu.hidden && !exampleMenu.contains(e.target) && e.target !== examplePicker) {
        closeExampleMenu();
    }
});

document.addEventListener("keydown", (e) => {
    if (e.key === "Escape" && !exampleMenu.hidden) closeExampleMenu();
});

exampleMenu.querySelectorAll(".example-item").forEach((btn) => {
    btn.addEventListener("click", () => {
        const key = btn.dataset.example;
        const src = EXAMPLES[key];
        if (typeof src === "string") {
            editor.setValue(src);
            // Mark the chosen example as checked in the menu.
            exampleMenu.querySelectorAll(".example-item").forEach((b) => {
                b.setAttribute("aria-checked", b === btn ? "true" : "false");
            });
            transpileNow();
        }
        closeExampleMenu();
    });
});

// ----- Share button -----------------------------------------------------
shareBtn.addEventListener("click", async () => {
    // Ensure URL has the latest source.
    updateUrlFragment(editor.getValue());
    const url = location.href;
    try {
        await navigator.clipboard.writeText(url);
        setStatus("ok", "share link copied to clipboard");
        // Bounce back to ok/error after a moment.
        window.setTimeout(() => {
            setStatus(lastTranspileResult && lastTranspileResult.ok ? "ok" : "error");
        }, 1800);
    } catch (err) {
        // Clipboard API may be blocked — fall back to selecting the URL bar.
        setStatus("error", `share: could not copy — copy from the URL bar (${err})`);
    }
});

// ----- Editor change handler (debounced) -------------------------------
editor.on("change", () => {
    // Clear any "picked" example checkmark — user is typing.
    exampleMenu.querySelectorAll(".example-item").forEach((b) => {
        b.setAttribute("aria-checked", "false");
    });
    scheduleTranspile();
});

// ----- Boot -------------------------------------------------------------
async function boot() {
    try {
        await init();
    } catch (err) {
        setStatus("error", `failed to load wasm: ${err}`);
        return;
    }

    // Mark page as ready — removes the loading reveal animation.
    bodyEl.dataset.state = "ready";

    // Restore from URL fragment, else load the default example.
    const restored = sourceFromUrlFragment();
    if (restored !== null) {
        editor.setValue(restored);
        // Mark the corresponding example as checked (if it matches one).
        const matchKey = Object.keys(EXAMPLES).find((k) => EXAMPLES[k] === restored);
        if (matchKey) {
            exampleMenu.querySelector(`[data-example="${matchKey}"]`)
                ?.setAttribute("aria-checked", "true");
        }
    } else {
        editor.setValue(EXAMPLES.fibonacci);
        exampleMenu.querySelector('[data-example="fibonacci"]')
            ?.setAttribute("aria-checked", "true");
    }

    // First transpile (skip debounce — instant feedback on load).
    transpileNow();

    // Give editor focus so the user can start typing immediately.
    editor.focus();
}

boot();
