//! Jupyter wire-protocol message types — the JSON header every message
//! carries + the multipart ZMQ frame layout.
//!
//! Per the [Jupyter messaging spec], a message is a multipart ZMQ
//! message with this layout:
//!
//! ```text
//!   [ ids..., <IDS|MSG>, hmac_hex, header, parent_header, metadata, content, ... ]
//!        ^          ^          ^        ^          ^             ^        ^
//!        |          |          |        |          |             |        |
//!   zero+ routing   delimiter  hex sig  JSON       JSON (may be   JSON    optional
//!   identity frames            or empty header     "{}")                 binary
//!                                if no                                blobs
//!                                auth
//! ```
//!
//! `header` and `parent_header` are both [`MessageHeader`] (the latter
//! echoes the request's header on a reply). `metadata` and `content`
//! are arbitrary JSON objects — we type them as
//! [`serde_json::Value`] to avoid baking a thousand content-specific
//! structs into the kernel.
//!
//! [Jupyter messaging spec]: https://jupyter-client.readthedocs.io/en/latest/messaging.html

use serde::{Deserialize, Serialize};
use serde_json::Value;

/// Header carried on every Jupyter wire message.
///
/// Mirrors `jupyter_client.jsonutil.extract_header`. Every field is a
/// string (per the spec) — even `date` (ISO-8601 UTC).
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct MessageHeader {
    /// Unique message id (UUID hex). Generated by the sender.
    #[serde(alias = "msg_id")]
    pub msg_id: String,
    /// Session id (UUID hex). Stable for the lifetime of a kernel
    /// instance — generated on boot, reused on every message the kernel
    /// emits so clients can correlate parent / child relationships.
    #[serde(alias = "session")]
    pub session: String,
    /// Username (Jupyter sets this to `"username"` by default — kernels
    /// echo it back on replies).
    #[serde(alias = "username")]
    pub username: String,
    /// ISO-8601 UTC timestamp (e.g. `"2026-07-20T12:34:56.789000Z"`).
    #[serde(alias = "date")]
    pub date: String,
    /// The message type (e.g. `"kernel_info_request"`,
    /// `"execute_request"`, `"shutdown_request"`).
    #[serde(alias = "msg_type")]
    pub msg_type: String,
    /// Messaging protocol version (e.g. `"5.3"`). The kernel
    /// advertises [`PROTOCOL_VERSION`] on its replies.
    #[serde(alias = "version")]
    pub version: String,
}

impl MessageHeader {
    /// Build a new header for a kernel-emitted reply, copying the
    /// `session` and `username` from the parent request (per the
    /// Jupyter spec) and stamping a fresh `msg_id` + `date`.
    ///
    /// `date` is set to the current UTC time via
    /// `chrono::Utc::now()`-equivalent; for unit-test determinism the
    /// function takes the date string as a parameter rather than
    /// computing it (the kernel loop passes a freshly-computed ISO
    /// string; tests pass a fixed string).
    #[must_use]
    pub fn new_reply(msg_type: &str, parent: &MessageHeader, date: &str, msg_id: &str) -> Self {
        Self {
            msg_id: msg_id.to_string(),
            session: parent.session.clone(),
            username: parent.username.clone(),
            date: date.to_string(),
            msg_type: msg_type.to_string(),
            version: PROTOCOL_VERSION.to_string(),
        }
    }
}

/// The Jupyter messaging protocol version this kernel advertises.
///
/// 5.3 is the current widely-deployed version (matches ipykernel 6.x
/// and jupyter_client 8.x as of 2026). Version 5.4 / 5.5 are drafts
/// with no breaking changes for the message types T129a handles
/// (kernel_info / execute / shutdown).
pub const PROTOCOL_VERSION: &str = "5.3";

/// A parsed Jupyter wire message — the post-delimiter 4 frames
/// (header / parent_header / metadata / content) plus the routing
/// identities (the `ids...` prefix) preserved for ROUTER socket
/// replies.
///
/// The hmac signature is stored separately (it's verified at parse
/// time and not needed downstream).
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct WireMessage {
    /// The ZMQ routing identity frames (everything before the
    /// `<IDS|MSG>` delimiter). Empty for non-ROUTER sockets; populated
    /// by shell / stdin / control sockets so replies can be addressed.
    pub identities: Vec<Vec<u8>>,
    /// The parsed `header` JSON frame.
    pub header: MessageHeader,
    /// The parsed `parent_header` JSON frame. Jupyter clients may send
    /// an empty object (`{}`) when there is no parent (e.g. the very
    /// first `kernel_info_request`).
    pub parent_header: Value,
    /// The parsed `metadata` JSON frame (always an object — `{}` if
    /// empty).
    pub metadata: Value,
    /// The parsed `content` JSON frame. Shape depends on `msg_type`.
    pub content: Value,
}

impl WireMessage {
    /// Serialize the 4 JSON frames back to bytes for HMAC signing
    /// (concatenated in spec order: header || parent_header ||
    /// metadata || content). Used by [`crate::hmac::sign`] /
    /// [`crate::hmac::verify`].
    ///
    /// # Errors
    ///
    /// Returns [`JupyterError::Json`](crate::JupyterError::Json) if any
    /// of the 4 frames fails to re-serialize (should not happen for a
    /// successfully-parsed message, but the contract is fallible).
    pub fn frames_for_signing(&self) -> crate::error::JupyterResult<Vec<Vec<u8>>> {
        let header_bytes = serde_json::to_vec(&self.header)?;
        let parent_bytes = serde_json::to_vec(&self.parent_header)?;
        let metadata_bytes = serde_json::to_vec(&self.metadata)?;
        let content_bytes = serde_json::to_vec(&self.content)?;
        Ok(vec![
            header_bytes,
            parent_bytes,
            metadata_bytes,
            content_bytes,
        ])
    }

    /// Build a new [`WireMessage`] for a reply: copies the request's
    /// `session` / `username` into a fresh header, uses the request's
    /// header as the parent_header, and resets metadata to `{}`. The
    /// caller provides the `content` value and the `msg_type` (which
    /// must match the content struct).
    #[must_use]
    pub fn new_reply(
        msg_type: &str,
        parent_request: &WireMessage,
        content: Value,
        date: &str,
        msg_id: &str,
    ) -> Self {
        let header = MessageHeader::new_reply(msg_type, &parent_request.header, date, msg_id);
        Self {
            identities: parent_request.identities.clone(),
            header,
            parent_header: serde_json::to_value(&parent_request.header).unwrap_or(Value::Null),
            metadata: Value::Object(serde_json::Map::new()),
            content,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    const HEADER_JSON: &str = r#"{
        "msg_id": "abc-123",
        "session": "sess-456",
        "username": "tester",
        "date": "2026-07-20T12:00:00.000000Z",
        "msg_type": "kernel_info_request",
        "version": "5.3"
    }"#;

    #[test]
    fn header_round_trips_via_serde() {
        let h: MessageHeader = serde_json::from_str(HEADER_JSON).expect("parse");
        assert_eq!(h.msg_type, "kernel_info_request");
        assert_eq!(h.version, "5.3");
        let re = serde_json::to_string(&h).expect("serialize");
        let h2: MessageHeader = serde_json::from_str(&re).expect("re-parse");
        assert_eq!(h, h2);
    }

    #[test]
    fn header_alias_msg_id_works() {
        // Some Jupyter clients use "msg_id" others use "msgid"; serde
        // alias covers both spellings. Same for msg_type/msgtype.
        let alt = r#"{
            "msg_id": "x",
            "session": "y",
            "username": "u",
            "date": "d",
            "msg_type": "m",
            "version": "5.3"
        }"#;
        let h: MessageHeader = serde_json::from_str(alt).expect("parse alt");
        assert_eq!(h.msg_id, "x");
        assert_eq!(h.msg_type, "m");
    }

    #[test]
    fn new_reply_inherits_session_username() {
        let parent: MessageHeader = serde_json::from_str(HEADER_JSON).expect("parse");
        let reply = MessageHeader::new_reply(
            "kernel_info_reply",
            &parent,
            "2026-07-20T12:00:01.000000Z",
            "reply-id",
        );
        assert_eq!(reply.msg_type, "kernel_info_reply");
        assert_eq!(reply.session, "sess-456");
        assert_eq!(reply.username, "tester");
        assert_eq!(reply.msg_id, "reply-id");
        assert_eq!(reply.version, PROTOCOL_VERSION);
    }

    #[test]
    fn frames_for_signing_round_trip() {
        let header: MessageHeader = serde_json::from_str(HEADER_JSON).expect("parse");
        let msg = WireMessage {
            identities: vec![],
            header,
            parent_header: serde_json::json!({}),
            metadata: serde_json::json!({}),
            content: serde_json::json!({}),
        };
        let frames = msg.frames_for_signing().expect("frames");
        assert_eq!(frames.len(), 4);
        // Header is the first frame and should parse back to the same struct.
        let h2: MessageHeader = serde_json::from_slice(&frames[0]).expect("header re-parse");
        assert_eq!(h2, msg.header);
    }
}
